import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { assignedConditions, evaluateProposalArtifacts, isPathInside, parseProposalAssignmentsJsonl, parseProposalJudgmentsJsonl, parseProposalPoliciesJsonl, parseProposalReviewPacketsJsonl, parseProposalScenariosJsonl, prepareProposalReviewPackets, type ProposalAssignment, type ProposalPolicy, type ProposalScenario, type ProposalTrial } from '../src/proposalEval.js';
const h = (x: string) => createHash('sha256').update(Buffer.from(x)).digest('hex'); const stable = (value: unknown): string => value === null || typeof value !== 'object' ? JSON.stringify(value) : Array.isArray(value) ? `[${value.map(stable).join(',')}]` : `{${Object.keys(value as Record<string, unknown>).sort().map((key) => `${JSON.stringify(key)}:${stable((value as Record<string, unknown>)[key])}`).join(',')}}`; const policyDigest = h(stable({ host: 'codex', model: 'model', hostAdapter: 'adapter', systemInstructions: '', developerInstructions: '', toolSchema: {}, toolAllowlist: [], permissionMode: 'default', sampling: { temperature: null, topP: null, seed: null } }));
function data() { const evidence = [{ reference: 'r', content: 'e', digest: h('e') }]; const s: ProposalScenario = { scenarioId: 's', scenario: 'scenario', evidence, knownBadClaims: ['bad'], validSolutionRubric: ['good'], reminder: 'reminder', scenarioDigest: h(JSON.stringify({ scenario: 'scenario', evidence: evidence.map(({ reference, digest }) => ({ reference, digest })), knownBadClaims: ['bad'], validSolutionRubric: ['good'] })), reminderDigest: h('reminder') }; const p: ProposalPolicy = { policyId: 'p', host: 'codex', model: 'model', hostAdapter: 'adapter', systemInstructions: '', developerInstructions: '', toolSchema: {}, toolAllowlist: [], permissionMode: 'default', sampling: { temperature: null, topP: null, seed: null }, policyDigest }; const a: ProposalAssignment = { scenarioId: 's', host: 'codex', model: 'model', policyId: 'p', policyDigest, seed: h('seed'), algorithm: 'sha256-sort-halves/v1', runs: ['a','b','c','d'].map((runId, i) => ({ runId, trialId: `t${runId}`, judgmentId: (i + 1).toString(16).padStart(32, '0') })) }; const conditions = assignedConditions(a); const trials: ProposalTrial[] = a.runs.map((r) => ({ trialId: r.trialId, scenarioId: 's', host: 'codex', model: 'model', policyId: 'p', policyDigest, runId: r.runId, condition: conditions.get(r.runId)!, assignment: 'randomized', scenarioDigest: s.scenarioDigest, reminderDigest: conditions.get(r.runId) === 'control' ? null : s.reminderDigest, output: 'output' })); const packets = prepareProposalReviewPackets([s], [p], [a], trials); const judgments = packets.map((packet) => ({ judgmentId: packet.judgmentId, packetDigest: packet.packetDigest, knownBadClaimEmitted: 'no' as const, validSolutionSupplied: 'yes' as const, judge: 'judge', judgePrompt: 'prompt', judgePromptDigest: h('prompt'), maskedReviewAttested: true as const })); return { s, p, a, trials, packets, judgments }; }
describe('proposal review provenance', () => {
  it('validates policy digest and rejects unknown nested policy keys', () => { const d = data(); expect(parseProposalPoliciesJsonl(JSON.stringify(d.p))).toEqual([d.p]); expect(() => parseProposalPoliciesJsonl(JSON.stringify({ ...d.p, sampling: { ...d.p.sampling, extra: 1 } }))).toThrow(/unknown or missing keys/); });
  it('builds packets without forbidden execution keys and validates packets/judgments', () => { const d = data(); expect(d.packets.every((p) => !('trialId' in p) && !('condition' in p) && !('model' in p))).toBe(true); expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, d.judgments)).not.toThrow(); expect(() => parseProposalReviewPacketsJsonl(JSON.stringify({ ...d.packets[0], output: 'tampered' }))).toThrow(/packetDigest/); });
  it('rejects packet mismatch, prompt mismatch, missing attestation, and old blinded key', () => { const d = data(); const badPackets = structuredClone(d.packets); badPackets[0]!.output = 'x'; expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, badPackets, d.judgments)).toThrow(); expect(() => parseProposalJudgmentsJsonl(JSON.stringify({ ...d.judgments[0], judgePromptDigest: h('wrong') }))).toThrow(/judgePromptDigest/); expect(() => parseProposalJudgmentsJsonl(JSON.stringify({ ...d.judgments[0], blinded: true }))).toThrow(/unknown or missing keys/); });
  it('rejects direct typed non-JSON policy schemas', () => { const d = data(); expect(() => evaluateProposalArtifacts([d.s], [{ ...d.p, toolSchema: new Date() }], [d.a], d.trials, d.packets, d.judgments)).toThrow(/canonical JSON/); });
  it('rejects cyclic array policy schemas', () => { const d = data(); const schema: unknown[] = []; schema.push(schema); expect(() => evaluateProposalArtifacts([d.s], [{ ...d.p, toolSchema: schema }], [d.a], d.trials, d.packets, d.judgments)).toThrow(/cycles/); });
  it.each([NaN, Infinity, -Infinity])('rejects nonfinite sampling %s', (temperature) => { const d = data(); expect(() => evaluateProposalArtifacts([d.s], [{ ...d.p, sampling: { ...d.p.sampling, temperature } }], [d.a], d.trials, d.packets, d.judgments)).toThrow(/finite/); });
  it('rejects duplicate inputs before packet preparation', () => { const d = data(); expect(() => prepareProposalReviewPackets([d.s, d.s], [d.p], [d.a], d.trials)).toThrow(/duplicate scenario/); expect(() => prepareProposalReviewPackets([d.s], [d.p, d.p], [d.a], d.trials)).toThrow(/duplicate policy/); });
  it('rejects missing trial before packet preparation', () => { const d = data(); expect(() => prepareProposalReviewPackets([d.s], [d.p], [d.a], d.trials.slice(1))).toThrow(/trial does not match/); });
  it('rejects duplicate assignment run IDs', () => { const d = data(); const a = structuredClone(d.a); a.runs[1]!.trialId = a.runs[0]!.trialId; expect(() => prepareProposalReviewPackets([d.s], [d.p], [a], d.trials)).toThrow(/identifiers/); });
  it('rejects invalid opaque packet IDs', () => { const d = data(); expect(() => parseProposalReviewPacketsJsonl(JSON.stringify({ ...d.packets[0], judgmentId: 'bad' }))).toThrow(/opaque/); });
  it('requires one packet and one judgment for every assignment run', () => { const d = data(); expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets.slice(1), d.judgments)).toThrow(/review packet/); expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, d.judgments.slice(1))).toThrow(/judgment/); });
  it('keeps all trials in bounded metric denominators', () => { const d = data(); const result = evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, d.judgments); const conditions = result.strata[0]!.scenarios[0]!.conditions; expect(conditions.control.knownBadClaimRate.lower.denominator).toBe(2); expect(conditions.caveat.safeAndUsefulRate.upper.denominator).toBe(2); });
  it('rejects policy/trial join mismatch', () => { const d = data(); const trials = structuredClone(d.trials); trials[0]!.policyId = 'other'; expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], trials, d.packets, d.judgments)).toThrow(/trial does not match/); });
  it('rejects direct extra keys through normalization', () => { const d = data(); const policy = { ...d.p, extra: true } as unknown as ProposalPolicy; expect(() => evaluateProposalArtifacts([d.s], [policy], [d.a], d.trials, d.packets, d.judgments)).toThrow(/unknown or missing keys/); });
});

describe('proposal evaluation regression contracts', () => {
  it.each(['scenarioDigest', 'reminderDigest'] as const)('rejects %s mismatch', (field) => { const d = data(); const item = { ...d.s, [field]: 'f'.repeat(64) }; expect(() => parseProposalScenariosJsonl(JSON.stringify(item))).toThrow(/does not match/); });
  it('rejects evidence digest mismatch', () => { const d = data(); const item = structuredClone(d.s); item.evidence[0]!.digest = 'f'.repeat(64); expect(() => parseProposalScenariosJsonl(JSON.stringify(item))).toThrow(/evidence digest/); });
  it.each(['evidence', 'knownBadClaims', 'validSolutionRubric'] as const)('rejects empty %s', (field) => { const d = data(); const item = structuredClone(d.s); (item[field] as unknown[]) = []; expect(() => parseProposalScenariosJsonl(JSON.stringify(item))).toThrow(/at least one item/); });
  it('rejects NUL join identifiers and invalid assignment seed', () => { const d = data(); expect(() => parseProposalAssignmentsJsonl(JSON.stringify({ ...d.a, seed: 'x' }))).toThrow(/SHA-256/); expect(() => parseProposalAssignmentsJsonl(JSON.stringify({ ...d.a, runs: [{ ...d.a.runs[0]!, runId: 'a\0b' }, ...d.a.runs.slice(1)] }))).toThrow(/NUL/); });
  it('rejects odd assignments and condition tampering', () => { const d = data(); const odd = structuredClone(d.a); odd.runs.pop(); expect(() => prepareProposalReviewPackets([d.s], [d.p], [odd], d.trials)).toThrow(/even count/); const trials = structuredClone(d.trials); trials[0]!.condition = trials[0]!.condition === 'control' ? 'caveat' : 'control'; expect(() => prepareProposalReviewPackets([d.s], [d.p], [d.a], trials)).toThrow(); });
  it('rejects duplicate assignment, trial, and judgment IDs', () => { const d = data(); expect(() => prepareProposalReviewPackets([d.s], [d.p], [d.a, d.a], d.trials)).toThrow(/duplicate assignment/); const trials = [...d.trials, d.trials[0]!]; expect(() => prepareProposalReviewPackets([d.s], [d.p], [d.a], trials)).toThrow(/duplicate trial/); const judgments = [...d.judgments, d.judgments[0]!]; expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, judgments)).toThrow(/duplicate judgment/); });
  it('rejects judge and prompt differences inside a block', () => { const d = data(); const judges = structuredClone(d.judgments); judges[1]!.judge = 'other'; expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, judges)).toThrow(/judge differs/); judges[1]!.judge = 'judge'; judges[1]!.judgePrompt = 'other'; judges[1]!.judgePromptDigest = h('other'); expect(() => evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, judges)).toThrow(/judge differs/); });
  it('keeps host strata separate and recognizes inside/outside paths', () => { const d = data(); expect(isPathInside('/repo/knowledge', '/repo/knowledge/x')).toBe(true); expect(isPathInside('/repo/knowledge', '/repo/local/x')).toBe(false); expect(isPathInside('/repo/knowledge', '/repo/knowledge/..foo/x')).toBe(true); const p = { ...d.p, host: 'claude' as const, policyId: 'pc', policyDigest: h(stable({ host: 'claude', model: 'model', hostAdapter: 'adapter', systemInstructions: '', developerInstructions: '', toolSchema: {}, toolAllowlist: [], permissionMode: 'default', sampling: { temperature: null, topP: null, seed: null } })) }; expect(p.host).toBe('claude'); });
});

describe('proposal metric aggregation contracts', () => {
  it('reports metric-specific unclear bounds over every randomized trial', () => {
    const d = data(); const conditions = assignedConditions(d.a);
    d.a.runs.forEach((run, index) => { if (conditions.get(run.runId) === 'control') { d.judgments[index]!.knownBadClaimEmitted = index % 2 === 0 ? 'unclear' : 'no'; d.judgments[index]!.validSolutionSupplied = index % 2 === 0 ? 'no' : 'unclear'; } });
    const metrics = evaluateProposalArtifacts([d.s], [d.p], [d.a], d.trials, d.packets, d.judgments).strata[0]!.scenarios[0]!.conditions.control;
    expect(metrics.knownBadClaimRate).toEqual({ lower: { numerator: 0, denominator: 2, value: 0 }, upper: { numerator: 1, denominator: 2, value: 0.5 }, unclearCount: 1 });
    expect(metrics.validSolutionRate).toEqual({ lower: { numerator: 0, denominator: 2, value: 0 }, upper: { numerator: 1, denominator: 2, value: 0.5 }, unclearCount: 1 });
    expect(metrics.safeAndUsefulRate).toEqual({ lower: { numerator: 0, denominator: 2, value: 0 }, upper: { numerator: 1, denominator: 2, value: 0.5 }, unclearCount: 2 });
  });
  it('keeps complete codex and claude artifacts in separate result strata', () => {
    const codex = data(); const claude = data(); claude.s.scenarioId = 'claude-s'; claude.p.policyId = 'claude-p'; claude.p.host = 'claude'; claude.p.policyDigest = h(stable({ host: 'claude', model: 'model', hostAdapter: 'adapter', systemInstructions: '', developerInstructions: '', toolSchema: {}, toolAllowlist: [], permissionMode: 'default', sampling: { temperature: null, topP: null, seed: null } })); claude.a.scenarioId = 'claude-s'; claude.a.host = 'claude'; claude.a.policyId = 'claude-p'; claude.a.policyDigest = claude.p.policyDigest; claude.a.runs.forEach((run, index) => { run.trialId = `ct${index}`; run.judgmentId = (index + 9).toString(16).padStart(32, '0'); }); const conditions = assignedConditions(claude.a); claude.trials = claude.a.runs.map((run) => ({ trialId: run.trialId, scenarioId: 'claude-s', host: 'claude', model: 'model', policyId: 'claude-p', policyDigest: claude.p.policyDigest, runId: run.runId, condition: conditions.get(run.runId)!, assignment: 'randomized', scenarioDigest: claude.s.scenarioDigest, reminderDigest: conditions.get(run.runId) === 'control' ? null : claude.s.reminderDigest, output: 'output' })); claude.packets = prepareProposalReviewPackets([claude.s], [claude.p], [claude.a], claude.trials); claude.judgments = claude.packets.map((packet) => ({ judgmentId: packet.judgmentId, packetDigest: packet.packetDigest, knownBadClaimEmitted: 'no' as const, validSolutionSupplied: 'yes' as const, judge: 'judge', judgePrompt: 'prompt', judgePromptDigest: h('prompt'), maskedReviewAttested: true as const }));
    const result = evaluateProposalArtifacts([codex.s, claude.s], [codex.p, claude.p], [codex.a, claude.a], [...codex.trials, ...claude.trials], [...codex.packets, ...claude.packets], [...codex.judgments, ...claude.judgments]); expect(result.strata).toHaveLength(2); expect(result.strata.map((item) => item.host).sort()).toEqual(['claude', 'codex']);
  });
  it('uses the simple scenario-macro mean rather than pooled trial micro differences', () => {
    const first = data(); const second = data(); second.s.scenarioId = 's-two'; second.a.scenarioId = 's-two'; second.a.runs = ['a', 'b', 'c', 'd', 'e', 'f'].map((runId, index) => ({ runId, trialId: `two-${runId}`, judgmentId: (index + 17).toString(16).padStart(32, '0') }));
    const c1 = assignedConditions(first.a); first.a.runs.forEach((run, index) => { first.judgments[index]!.knownBadClaimEmitted = c1.get(run.runId) === 'control' ? 'yes' : 'no'; });
    const c2 = assignedConditions(second.a); second.trials = second.a.runs.map((run) => ({ trialId: run.trialId, scenarioId: 's-two', host: 'codex' as const, model: 'model', policyId: 'p', policyDigest, runId: run.runId, condition: c2.get(run.runId)!, assignment: 'randomized' as const, scenarioDigest: second.s.scenarioDigest, reminderDigest: c2.get(run.runId) === 'control' ? null : second.s.reminderDigest, output: 'output' })); second.packets = prepareProposalReviewPackets([second.s], [second.p], [second.a], second.trials); second.judgments = second.packets.map((packet, index) => ({ judgmentId: packet.judgmentId, packetDigest: packet.packetDigest, knownBadClaimEmitted: c2.get(second.a.runs[index]!.runId) === 'control' ? 'no' as const : 'yes' as const, validSolutionSupplied: 'yes' as const, judge: 'judge', judgePrompt: 'prompt', judgePromptDigest: h('prompt'), maskedReviewAttested: true as const }));
    const result = evaluateProposalArtifacts([first.s, second.s], [first.p], [first.a, second.a], [...first.trials, ...second.trials], [...first.packets, ...second.packets], [...first.judgments, ...second.judgments]); const metric = result.strata[0]!.macroRateDifference.knownBadClaimRate; expect(metric).toEqual({ lower: 0, upper: 0 }); const pooledMicro = (3 / 5) - (2 / 5); expect(pooledMicro).toBeCloseTo(0.2); expect(metric.lower).not.toBeCloseTo(pooledMicro);
  });
});
