import { createHash } from 'node:crypto';
import { describe, expect, it } from 'vitest';
import { assignedConditions, type ProposalAssignment, type ProposalPolicy, type ProposalScenario } from '../src/proposalEval.js';
import { PROPOSAL_EXECUTION_SCHEMA_VERSION, buildProposalRequestBytes, canonicalProposalExecutionJson, expectedProposalExecutionArgv, parseClaudeProposalExecutionJsonl, parseCodexProposalExecutionJsonl, parseProposalExecutionPlansJsonl, parseProposalExecutionReceiptsJsonl, prepareProposalExecutionPlans, proposalAssignmentDigest, summarizeProposalExecutionStatuses, validateProposalExecutionPlans, validateProposalExecutionProvenance } from '../src/proposalExecution.js';

const h = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
function fixture() {
  const evidence = [{ reference: 'r', content: 'e', digest: h('e') }];
  const scenario: ProposalScenario = { scenarioId: 'scenario', scenario: 'prompt', evidence, knownBadClaims: ['bad'], validSolutionRubric: ['good'], reminder: 'remember', scenarioDigest: h(JSON.stringify({ scenario: 'prompt', evidence: evidence.map(({ reference, digest }) => ({ reference, digest })), knownBadClaims: ['bad'], validSolutionRubric: ['good'] })), reminderDigest: h('remember') };
  const policyData = { host: 'codex', model: 'model', hostAdapter: 'codex-cli/prompt-injected-reminder/v1', systemInstructions: '', developerInstructions: '', toolSchema: {}, toolAllowlist: [], permissionMode: 'read-only-no-tools', sampling: { temperature: null, topP: null, seed: null } };
  const policy: ProposalPolicy = { policyId: 'policy', ...policyData, policyDigest: h(canonicalProposalExecutionJson(policyData)) };
  const assignment: ProposalAssignment = { scenarioId: scenario.scenarioId, host: 'codex', model: 'model', policyId: policy.policyId, policyDigest: policy.policyDigest, seed: h('seed'), algorithm: 'sha256-sort-halves/v1', runs: ['a', 'b', 'c', 'd'].map((runId, index) => ({ trialId: `trial-${runId}`, judgmentId: `${index + 1}`.padStart(32, '0'), runId })) };
  const conditions = assignedConditions(assignment);
  const plans = assignment.runs.map((run) => {
    const condition = conditions.get(run.runId)!; const bytes = buildProposalRequestBytes(scenario, condition); const environment = { values: { HOME: '/tmp/home', CODEX_HOME: '/tmp/home/.codex', PATH: '/bin', TMPDIR: '/tmp/work', LANG: 'C.UTF-8' }, credentialSlotId: h('codex\0/tmp/home/.codex'), endpoint: 'default' as const, organization: null, project: null }; const invocationData = { executablePath: '/usr/bin/codex', executableDigest: h('binary'), argv: ['exec', '--json', '--ephemeral', '--ignore-user-config', '--ignore-rules', '--sandbox', 'read-only', '--skip-git-repo-check', '--model', 'model', '-'], cwdPath: '/tmp/work', environment }; const invocation = { ...invocationData, digest: h(canonicalProposalExecutionJson(invocationData)) };
    const data = { schemaVersion: PROPOSAL_EXECUTION_SCHEMA_VERSION, trialId: run.trialId, judgmentId: run.judgmentId, runId: run.runId, scenarioId: scenario.scenarioId, host: 'codex' as const, policyId: policy.policyId, condition, adapter: 'codex-cli' as const, adapterVersion: '1', requestedModel: policy.model, scenarioDigest: scenario.scenarioDigest, policyDigest: policy.policyDigest, assignmentDigest: proposalAssignmentDigest(assignment), request: { bytesBase64: bytes.toString('base64'), byteLength: bytes.length, digest: h(bytes), channel: 'stdin' as const, envelope: 'prompt-injected-reminder/v1' as const }, invocation };
    return { ...data, planDigest: h(canonicalProposalExecutionJson(data)) };
  });
  const receipts = plans.map((plan) => { const data = { schemaVersion: PROPOSAL_EXECUTION_SCHEMA_VERSION, trialId: plan.trialId, runId: plan.runId, planDigest: plan.planDigest, invocationDigest: plan.invocation.digest, status: 'completed' as const, startedAt: '2026-07-13T01:02:03.000Z', completedAt: '2026-07-13T01:02:04.000Z', cliVersion: '1', exitCode: 0, providerRunId: 'provider', reportedModel: null, modelProvenance: 'requested_only' as const, requestSubmission: 'passed_to_spawn_sync' as const, submittedRequestDigest: plan.request.digest, submittedByteLength: plan.request.byteLength, rawStdoutDigest: h('stdout'), rawStderrDigest: h('stderr'), outputDigest: h('output') }; return { ...data, receiptDigest: h(canonicalProposalExecutionJson(data)) }; });
  return { scenario, policy, assignment, plans, receipts };
}
const planJson = (plan: object) => JSON.stringify(plan);
const receiptJson = (receipt: object) => JSON.stringify(receipt);
function resealPlan(plan: any, changes: any): any { const merged = { ...plan, ...changes, request: { ...plan.request, ...changes.request }, invocation: { ...plan.invocation, ...changes.invocation, environment: { ...plan.invocation.environment, ...changes.invocation?.environment } } }; const { digest: ignored, ...invocationData } = merged.invocation; merged.invocation.digest = h(canonicalProposalExecutionJson(invocationData)); const { planDigest: ignoredPlan, ...planData } = merged; return { ...merged, planDigest: h(canonicalProposalExecutionJson(planData)) }; }
function resealReceipt(receipt: any, changes: any): any { const data = { ...receipt, ...changes }; delete data.receiptDigest; return { ...data, receiptDigest: h(canonicalProposalExecutionJson(data)) }; }
function resealPolicy(policy: ProposalPolicy, changes: Record<string, unknown>): ProposalPolicy { const data = { host: policy.host, model: policy.model, hostAdapter: policy.hostAdapter, systemInstructions: policy.systemInstructions, developerInstructions: policy.developerInstructions, toolSchema: policy.toolSchema, toolAllowlist: policy.toolAllowlist, permissionMode: policy.permissionMode, sampling: policy.sampling, ...changes }; return { policyId: policy.policyId, ...data, policyDigest: h(canonicalProposalExecutionJson(data)) } as ProposalPolicy; }
describe('proposal execution artifacts', () => {
  it('accepts and joins a four-run manifest exactly', () => { const d = fixture(); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, d.receipts)).not.toThrow(); });
  it('rejects schema/nested-key, digest, base64 and path tampering', () => { const d = fixture(); const p = d.plans[0]!; expect(() => parseProposalExecutionPlansJsonl(planJson({ ...p, unexpected: true }))).toThrow(/keys/); expect(() => parseProposalExecutionPlansJsonl(planJson({ ...p, request: { ...p.request, bytesBase64: `${p.request.bytesBase64}=` } }))).toThrow(/request bytes/); expect(() => parseProposalExecutionPlansJsonl(planJson({ ...p, invocation: { ...p.invocation, cwdPath: 'relative' } }))).toThrow(/plan fields|digest/); expect(() => parseProposalExecutionPlansJsonl(planJson({ ...p, scenarioDigest: h('tampered') }))).toThrow(/planDigest/); expect(() => parseProposalExecutionPlansJsonl(planJson({ ...p, invocation: { ...p.invocation, argv: ['x\0'] } }))).toThrow(/argv/); });
  it('rejects receipt timestamp and status invariant violations', () => { const d = fixture(); const r = d.receipts[0]!; expect(() => parseProposalExecutionReceiptsJsonl(receiptJson({ ...r, startedAt: '2026-7-1' }))).toThrow(/RFC3339/); expect(() => parseProposalExecutionReceiptsJsonl(receiptJson({ ...r, status: 'completed', exitCode: 1 }))).toThrow(/invariant/); expect(() => parseProposalExecutionReceiptsJsonl(receiptJson({ ...r, status: 'nonzero_exit', exitCode: 1, outputDigest: h('x') }))).toThrow(/invariant/); });
  it('rejects duplicate, missing and extra join records plus policy and assignment changes', () => { const d = fixture(); const changedPolicyData = { host: d.policy.host, model: d.policy.model, hostAdapter: d.policy.hostAdapter, systemInstructions: d.policy.systemInstructions, developerInstructions: d.policy.developerInstructions, toolSchema: null, toolAllowlist: d.policy.toolAllowlist, permissionMode: d.policy.permissionMode, sampling: d.policy.sampling }; const changedPolicy = { ...d.policy, toolSchema: null, policyDigest: h(canonicalProposalExecutionJson(changedPolicyData)) }; expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans.slice(1), d.receipts)).toThrow(/every assignment/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], [...d.plans, d.plans[0]!], d.receipts)).toThrow(/mismatch/); expect(() => validateProposalExecutionProvenance([d.scenario], [changedPolicy], [d.assignment], d.plans, d.receipts)).toThrow(/fixed/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [{ ...d.assignment, seed: h('other') }], d.plans, d.receipts)).toThrow(/mismatch/); });
  it('counts unsuccessful caveat attempts as unclear against all plans', () => { const d = fixture(); const caveat = d.plans.find((plan) => plan.condition === 'caveat')!; const changed = d.receipts.map((receipt) => receipt.trialId !== caveat.trialId ? receipt : (() => { const data = { ...receipt, status: 'tool_attempted' as const, outputDigest: null }; return { ...data, receiptDigest: h(canonicalProposalExecutionJson(data)) }; })()); const summary = summarizeProposalExecutionStatuses(d.plans, changed); expect(summary.caveat).toMatchObject({ denominator: 2, unclearCount: 1, statuses: { completed: 1, tool_attempted: 1 } }); });
  it('rejects cyclic arrays and nonfinite canonical JSON', () => { const loop: unknown[] = []; loop.push(loop); expect(() => canonicalProposalExecutionJson(loop)).toThrow(/cycles/); expect(() => canonicalProposalExecutionJson({ value: Infinity })).toThrow(/finite/); });
  it('requires zero exit for protocol and tool attempts and completed output identity', () => { const r = fixture().receipts[0]!; for (const changes of [{ status: 'protocol_error', exitCode: 1, outputDigest: null }, { status: 'tool_attempted', exitCode: null, outputDigest: null }, { providerRunId: null }, { reportedModel: 'model' }, { modelProvenance: 'provider_reported' }, { outputDigest: null }, { requestSubmission: 'not_attempted', submittedRequestDigest: null, submittedByteLength: null }]) expect(() => parseProposalExecutionReceiptsJsonl(receiptJson(resealReceipt(r, changes)))).toThrow(/invariant/); expect(parseProposalExecutionReceiptsJsonl(receiptJson(r))[0]!.reportedModel).toBeNull(); });
  it('rejects unknown nested plan and receipt keys after their outer fields are otherwise valid', () => { const d = fixture(); const p = d.plans[0]!; expect(() => parseProposalExecutionPlansJsonl(planJson(resealPlan(p, { request: { extra: true } })))).toThrow(/request has unknown/); expect(() => parseProposalExecutionPlansJsonl(planJson(resealPlan(p, { invocation: { environment: { extra: true } } })))).toThrow(/environment has unknown/); expect(() => parseProposalExecutionReceiptsJsonl(receiptJson({ ...d.receipts[0]!, extra: true }))).toThrow(/receipt has unknown/); });
  it('rejects duplicate scenario, policy, assignment block, and globally repeated run identifiers', () => { const d = fixture(); expect(() => validateProposalExecutionProvenance([d.scenario, d.scenario], [d.policy], [d.assignment], d.plans, d.receipts)).toThrow(/duplicate scenarioId/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy, d.policy], [d.assignment], d.plans, d.receipts)).toThrow(/duplicate policyId/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment, d.assignment], d.plans, d.receipts)).toThrow(/duplicate assignment block/); const repeated = { ...d.assignment, runs: d.assignment.runs.map((run, index) => index === 1 ? { ...run, runId: d.assignment.runs[0]!.runId } : run) }; expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [repeated], d.plans, d.receipts)).toThrow(/identifiers/); });
  it('rejects missing, extra, duplicate, and request-join-tampered receipts', () => { const d = fixture(); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, d.receipts.slice(1))).toThrow(/every assignment run requires exactly one receipt/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, [...d.receipts, d.receipts[0]!])).toThrow(/receipt provenance/); const extra = resealReceipt({ ...d.receipts[0]!, trialId: 'other' }, {}); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, [...d.receipts.slice(1), extra])).toThrow(/receipt provenance/); for (const changes of [{ submittedRequestDigest: h('bad') }, { submittedByteLength: d.receipts[0]!.submittedByteLength! + 1 }]) expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, [resealReceipt(d.receipts[0]!, changes), ...d.receipts.slice(1)])).toThrow(/receipt provenance/); });
  it('rejects resealed host, adapter, model, condition and reminder-request provenance changes', () => { const d = fixture(); const p = d.plans[0]!; const altered = (changed: any) => [resealPlan(p, changed), ...d.plans.slice(1)]; expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], altered({ host: 'claude' }), d.receipts)).toThrow(/plan fields|plan provenance/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], altered({ adapter: 'claude-cli' }), d.receipts)).toThrow(/plan fields|plan provenance/); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], altered({ requestedModel: 'other' }), d.receipts)).toThrow(/plan fields|plan provenance/); const otherCondition = p.condition === 'control' ? 'caveat' : 'control'; expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], altered({ condition: otherCondition }), d.receipts)).toThrow(/plan fields|plan provenance/); const bytes = Buffer.from('prompt\n\n<caveat-reminder>\nwrong\n</caveat-reminder>'); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], altered({ request: { bytesBase64: bytes.toString('base64'), byteLength: bytes.length, digest: h(bytes) } }), d.receipts)).toThrow(/plan provenance/); });
  it('rejects each nonempty CLI-v1 policy control with a valid policy digest', () => { const d = fixture(); for (const changes of [{ systemInstructions: 'x' }, { developerInstructions: 'x' }, { toolAllowlist: ['tool'] }, { sampling: { temperature: 1, topP: null, seed: null } }]) expect(() => validateProposalExecutionProvenance([d.scenario], [resealPolicy(d.policy, changes)], [d.assignment], d.plans, d.receipts)).toThrow(/fixed/); });
  it('prepares a runtime-exact phase-one plan and enforces the expected argv/environment', () => { const d = fixture(); const runtimes = d.assignment.runs.map((run) => ({ trialId: run.trialId, adapterVersion: 'v', executablePath: '/usr/bin/codex', executableDigest: h('bin'), cwdPath: `/tmp/${run.runId}`, environment: { values: { HOME: '/tmp/home', CODEX_HOME: '/tmp/home/.codex', PATH: '/bin', TMPDIR: `/tmp/${run.runId}`, LANG: 'C.UTF-8' }, credentialSlotId: h('codex\0/tmp/home/.codex'), endpoint: 'default' as const, organization: null, project: null } })); const plans = prepareProposalExecutionPlans([d.scenario], [d.policy], [d.assignment], runtimes); expect(plans).toHaveLength(4); expect(plans[0]!.invocation.argv).toEqual(expectedProposalExecutionArgv('codex', 'model')); expect(() => validateProposalExecutionPlans([d.scenario], [d.policy], [d.assignment], plans)).not.toThrow(); expect(() => prepareProposalExecutionPlans([d.scenario], [d.policy], [d.assignment], runtimes.slice(1))).toThrow(/requires one runtime/); expect(() => prepareProposalExecutionPlans([d.scenario], [d.policy], [d.assignment], [...runtimes, { ...runtimes[0]!, trialId: 'extra' }])).toThrow(/extra trial/); });
  it('accepts the canonical empty --tools value and exact legacy/current Claude auth environments', () => { const d = fixture(); const model = 'claude-sonnet-4-6'; const policy = resealPolicy(d.policy, { host: 'claude', model, hostAdapter: 'claude-cli/prompt-injected-reminder/v1' }); const assignment = { ...d.assignment, host: 'claude' as const, model, policyDigest: policy.policyDigest }; for (const authenticated of [false, true]) { const runtimes = assignment.runs.map((run) => { const values = authenticated ? { HOME: '/tmp/home', PATH: '/bin', TMPDIR: `/tmp/${run.runId}`, LANG: 'C.UTF-8', USER: 'owner', LOGNAME: 'owner' } : { HOME: '/tmp/home', PATH: '/bin', TMPDIR: `/tmp/${run.runId}`, LANG: 'C.UTF-8' }; const identity = authenticated ? '/tmp/home\0owner\0owner' : '/tmp/home'; return { trialId: run.trialId, adapterVersion: 'v', executablePath: '/usr/bin/claude', executableDigest: h('bin'), cwdPath: `/tmp/${run.runId}`, environment: { values, credentialSlotId: h(`claude\0${identity}`), endpoint: 'default' as const, organization: null, project: null } }; }); const plans = prepareProposalExecutionPlans([d.scenario], [policy], [assignment], runtimes); expect(plans[0]!.invocation.argv).toEqual(expectedProposalExecutionArgv('claude', model)); expect(plans[0]!.invocation.argv).toContain(''); expect(() => validateProposalExecutionPlans([d.scenario], [policy], [assignment], plans)).not.toThrow(); } });
  it('rejects argv and exact environment mismatches even with resealed digests', () => { const d = fixture(); const p = d.plans[0]!; expect(() => parseProposalExecutionPlansJsonl(planJson(resealPlan(p, { invocation: { argv: ['exec'] } })))).toThrow(/plan fields/); expect(() => parseProposalExecutionPlansJsonl(planJson(resealPlan(p, { invocation: { environment: { values: { ...p.invocation.environment.values, EXTRA: 'x' } } } })))).toThrow(/plan fields/); for (const environment of [{ ...p.invocation.environment, values: { ...p.invocation.environment.values, HOME: 'relative' } }, { ...p.invocation.environment, values: { ...p.invocation.environment.values, CODEX_HOME: 'relative' } }, { ...p.invocation.environment, values: { ...p.invocation.environment.values, TMPDIR: '/other' } }, { ...p.invocation.environment, values: { ...p.invocation.environment.values, LANG: 'en_US.UTF-8' } }, { ...p.invocation.environment, credentialSlotId: h('wrong') }]) expect(() => parseProposalExecutionPlansJsonl(planJson(resealPlan(p, { invocation: { environment } })))).toThrow(/plan fields/); });
  it('rejects runtime and CLI version differences inside a comparison block', () => { const d = fixture(); const changedPlan = resealPlan(d.plans[0]!, { adapterVersion: 'other-version' }); expect(() => validateProposalExecutionPlans([d.scenario], [d.policy], [d.assignment], [changedPlan, ...d.plans.slice(1)])).toThrow(/runtime differs/); const receipt = resealReceipt(d.receipts[0]!, { cliVersion: 'other-version' }); expect(() => validateProposalExecutionProvenance([d.scenario], [d.policy], [d.assignment], d.plans, [receipt, ...d.receipts.slice(1)])).toThrow(/receipt provenance/); });
});

describe('proposal execution adapter protocols', () => {
  const jsonl = (records: unknown[]) => `${records.map(JSON.stringify).join('\n')}\n`;
  it('takes the last completed Codex agent message and records requested-only model provenance', () => {
    const parsed = parseCodexProposalExecutionJsonl(jsonl([
      { type: 'thread.started', thread_id: 'thread-1' },
      { type: 'turn.started' },
      { type: 'item.completed', item: { id: 'item-1', type: 'agent_message', text: 'draft' } },
      { type: 'item.completed', item: { id: 'item-2', type: 'reasoning', text: 'summary' } },
      { type: 'item.completed', item: { id: 'item-3', type: 'agent_message', text: 'final' } },
      { type: 'turn.completed', usage: { input_tokens: 1, cached_input_tokens: 0, output_tokens: 1, reasoning_output_tokens: 0 } },
    ]));
    expect(parsed).toEqual({ status: 'completed', providerRunId: 'thread-1', reportedModel: null, modelProvenance: 'requested_only', output: 'final' });
  });
  it('fails Codex closed on tools, errors, malformed order, unknown events, and missing terminal output', () => {
    const base = [{ type: 'thread.started', thread_id: 'thread-1' }, { type: 'turn.started' }];
    expect(parseCodexProposalExecutionJsonl(jsonl([...base, { type: 'item.started', item: { id: 'x', type: 'command_execution' } }, { type: 'turn.completed', usage: {} }])).status).toBe('tool_attempted');
    for (const tail of [
      [{ type: 'error', message: 'failure' }, { type: 'turn.completed', usage: {} }],
      [{ type: 'future.event' }, { type: 'turn.completed', usage: {} }],
      [{ type: 'turn.completed', usage: {} }],
      [{ type: 'item.completed', item: { id: 'x', type: 'agent_message', text: 'x' } }],
    ]) expect(parseCodexProposalExecutionJsonl(jsonl([...base, ...tail])).status).toBe('protocol_error');
    expect(parseCodexProposalExecutionJsonl('{')).toMatchObject({ status: 'protocol_error', output: null });
  });
  it('joins Claude init, assistant, and result model evidence', () => {
    const parsed = parseClaudeProposalExecutionJsonl(jsonl([
      { type: 'system', subtype: 'init', model: 'claude-sonnet-4-6', session_id: 'session-1' },
      { type: 'system', subtype: 'thinking_tokens', estimated_tokens: 50, estimated_tokens_delta: 50, session_id: 'session-1' },
      { type: 'assistant', session_id: 'session-1', message: { model: 'claude-sonnet-4-6', content: [{ type: 'thinking', thinking: 'x' }, { type: 'text', text: 'answer' }] } },
      { type: 'rate_limit_event', session_id: 'session-1', rate_limit_info: { status: 'allowed' } },
      { type: 'result', subtype: 'success', is_error: false, result: 'answer', modelUsage: { 'claude-haiku-4-5-20251001': { inputTokens: 1 }, 'claude-sonnet-4-6': { inputTokens: 1 } }, permission_denials: [], session_id: 'session-1' },
    ]), 'claude-sonnet-4-6');
    expect(parsed).toEqual({ status: 'completed', providerRunId: 'session-1', reportedModel: 'claude-sonnet-4-6', modelProvenance: 'provider_reported', output: 'answer' });
  });
  it('fails Claude closed on tool use, denials, model mixing, session mismatch, and error results', () => {
    const init = { type: 'system', subtype: 'init', model: 'model-a', session_id: 'session-1' }; const assistant = { type: 'assistant', session_id: 'session-1', message: { model: 'model-a', content: [{ type: 'text', text: 'answer' }] } }; const result = { type: 'result', subtype: 'success', is_error: false, result: 'answer', modelUsage: { 'model-a': {} }, permission_denials: [], session_id: 'session-1' };
    expect(parseClaudeProposalExecutionJsonl(jsonl([init, { ...assistant, message: { model: 'model-a', content: [{ type: 'tool_use', name: 'Read' }] } }, result]), 'model-a').status).toBe('tool_attempted');
    expect(parseClaudeProposalExecutionJsonl(jsonl([init, assistant, { ...result, permission_denials: [{}] }]), 'model-a').status).toBe('tool_attempted');
    expect(parseClaudeProposalExecutionJsonl(jsonl([init, { type: 'system', subtype: 'thinking_tokens', estimated_tokens: -1, estimated_tokens_delta: 1, session_id: 'session-1' }, assistant, result]), 'model-a').status).toBe('protocol_error');
    expect(parseClaudeProposalExecutionJsonl(jsonl([init, { ...assistant, message: { ...assistant.message, model: 'model-b' } }, { ...result, modelUsage: { 'model-a': {}, 'model-b': {} } }]), 'model-a').status).toBe('protocol_error');
    for (const changed of [
      { ...result, modelUsage: { 'model-b': {} } },
      { ...result, session_id: 'other' },
      { ...result, subtype: 'error_during_execution', is_error: true },
    ]) expect(parseClaudeProposalExecutionJsonl(jsonl([init, assistant, changed]), 'model-a').status).toBe('protocol_error');
  });
});
