import { createHash } from 'node:crypto';
import { basename, isAbsolute } from 'node:path';
import { assignedConditions, parseProposalAssignmentsJsonl, parseProposalPoliciesJsonl, parseProposalScenariosJsonl, type ProposalAssignment, type ProposalCondition, type ProposalPolicy, type ProposalScenario } from './proposalEval.js';

export const PROPOSAL_EXECUTION_SCHEMA_VERSION = 'proposal-execution/v1';
export type ProposalExecutionAdapter = 'codex-cli' | 'claude-cli';
export type ProposalExecutionStatus = 'completed' | 'unavailable' | 'protocol_error' | 'tool_attempted' | 'nonzero_exit';
export type ProposalExecutionModelProvenance = 'provider_reported' | 'requested_only';
export type ProposalExecutionRequestSubmission = 'not_attempted' | 'passed_to_spawn_sync' | 'indeterminate';
export interface ParsedProposalExecutionOutput { status: 'completed' | 'protocol_error' | 'tool_attempted'; providerRunId: string | null; reportedModel: string | null; modelProvenance: ProposalExecutionModelProvenance; output: string | null; }
export interface ProposalExecutionRuntime { trialId: string; adapterVersion: string; executablePath: string; executableDigest: string; cwdPath: string; environment: { values: Record<string, string>; credentialSlotId: string; endpoint: 'default'; organization: null; project: null }; }
export interface ProposalExecutionPlan { schemaVersion: typeof PROPOSAL_EXECUTION_SCHEMA_VERSION; trialId: string; judgmentId: string; runId: string; scenarioId: string; host: 'claude' | 'codex'; policyId: string; condition: ProposalCondition; adapter: ProposalExecutionAdapter; adapterVersion: string; requestedModel: string; scenarioDigest: string; policyDigest: string; assignmentDigest: string; request: { bytesBase64: string; byteLength: number; digest: string; channel: 'stdin'; envelope: 'prompt-injected-reminder/v1' }; invocation: { executablePath: string; executableDigest: string; argv: string[]; cwdPath: string; environment: { values: Record<string, string>; credentialSlotId: string; endpoint: string | null; organization: string | null; project: string | null }; digest: string }; planDigest: string; }
export interface ProposalExecutionReceipt { schemaVersion: typeof PROPOSAL_EXECUTION_SCHEMA_VERSION; trialId: string; runId: string; planDigest: string; invocationDigest: string; status: ProposalExecutionStatus; startedAt: string; completedAt: string; cliVersion: string; exitCode: number | null; providerRunId: string | null; reportedModel: string | null; modelProvenance: ProposalExecutionModelProvenance; requestSubmission: ProposalExecutionRequestSubmission; submittedRequestDigest: string | null; submittedByteLength: number | null; rawStdoutDigest: string; rawStderrDigest: string; outputDigest: string | null; receiptDigest: string; }
export class ProposalExecutionError extends Error { constructor(line: number | null, reason: string, count = 1) { super(`proposal execution artifact mismatch: ${line === null ? 'aggregate' : `line ${line}`}; count ${count}; ${reason}`); this.name = 'ProposalExecutionError'; } }

const DIGEST = /^[0-9a-f]{64}$/;
const sha = (value: string | Buffer) => createHash('sha256').update(value).digest('hex');
const record = (value: unknown): value is Record<string, unknown> => typeof value === 'object' && value !== null && !Array.isArray(value) && Object.getPrototypeOf(value) === Object.prototype;
function exact(value: Record<string, unknown>, fields: string[], line: number, name: string): void { const actual = Object.keys(value); if (actual.length !== fields.length || actual.some((field) => !fields.includes(field))) throw new ProposalExecutionError(line, `${name} has unknown or missing keys`); }
function string(value: unknown, line: number, field: string): string { if (typeof value !== 'string' || value.length === 0 || value.includes('\0')) throw new ProposalExecutionError(line, `${field} must be a nonempty NUL-free string`); return value; }
function nullableString(value: unknown, line: number, field: string): string | null { return value === null ? null : string(value, line, field); }
function digest(value: unknown, line: number, field: string): string { const result = string(value, line, field); if (!DIGEST.test(result)) throw new ProposalExecutionError(line, `${field} must be a lowercase SHA-256 digest`); return result; }
function integer(value: unknown, line: number, field: string, nonnegative = false): number { if (typeof value !== 'number' || !Number.isFinite(value) || !Number.isInteger(value) || (nonnegative && value < 0)) throw new ProposalExecutionError(line, `${field} must be a ${nonnegative ? 'nonnegative ' : ''}finite integer`); return value; }

/** Canonical JSON used by all execution digests. */
export function canonicalProposalExecutionJson(value: unknown, seen = new Set<object>()): string {
  if (value === null || typeof value === 'string' || typeof value === 'boolean') return JSON.stringify(value);
  if (typeof value === 'number') { if (!Number.isFinite(value)) throw new ProposalExecutionError(null, 'canonical JSON requires finite numbers'); return JSON.stringify(value); }
  if (Array.isArray(value)) { if (seen.has(value)) throw new ProposalExecutionError(null, 'canonical JSON rejects cycles'); seen.add(value); const result = `[${value.map((item) => canonicalProposalExecutionJson(item, seen)).join(',')}]`; seen.delete(value); return result; }
  if (!record(value)) throw new ProposalExecutionError(null, 'canonical JSON requires acyclic plain values');
  if (seen.has(value)) throw new ProposalExecutionError(null, 'canonical JSON rejects cycles'); seen.add(value);
  const result = `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${canonicalProposalExecutionJson(value[key], seen)}`).join(',')}}`;
  seen.delete(value); return result;
}
export const proposalAssignmentDigest = (assignment: ProposalAssignment): string => sha(canonicalProposalExecutionJson(assignment));
export function proposalExecutionRuntimeDigest(plan: ProposalExecutionPlan): string { const environment = plan.invocation.environment; const values = Object.fromEntries(Object.entries(environment.values).filter(([key]) => key !== 'TMPDIR')); return sha(canonicalProposalExecutionJson({ adapter: plan.adapter, adapterVersion: plan.adapterVersion, executablePath: plan.invocation.executablePath, executableDigest: plan.invocation.executableDigest, argv: plan.invocation.argv, environment: { values, credentialSlotId: environment.credentialSlotId, endpoint: environment.endpoint, organization: environment.organization, project: environment.project } })); }
export function expectedProposalExecutionArgv(host: 'codex' | 'claude', model: string): string[] { return host === 'codex' ? ['exec', '--json', '--ephemeral', '--ignore-user-config', '--ignore-rules', '--sandbox', 'read-only', '--skip-git-repo-check', '--model', model, '-'] : ['-p', '--output-format', 'stream-json', '--verbose', '--safe-mode', '--tools', '', '--no-session-persistence', '--model', model]; }

function parsePlan(value: unknown, line: number): ProposalExecutionPlan {
  if (!record(value)) throw new ProposalExecutionError(line, 'plan must be a plain object');
  exact(value, ['schemaVersion', 'trialId', 'judgmentId', 'runId', 'scenarioId', 'host', 'policyId', 'condition', 'adapter', 'adapterVersion', 'requestedModel', 'scenarioDigest', 'policyDigest', 'assignmentDigest', 'request', 'invocation', 'planDigest'], line, 'plan');
  if (value.schemaVersion !== PROPOSAL_EXECUTION_SCHEMA_VERSION) throw new ProposalExecutionError(line, 'plan schemaVersion is invalid');
  if (!record(value.request) || !record(value.invocation) || !record(value.invocation.environment) || !record(value.invocation.environment.values)) throw new ProposalExecutionError(line, 'plan nested fields must be plain objects');
  exact(value.request, ['bytesBase64', 'byteLength', 'digest', 'channel', 'envelope'], line, 'request'); exact(value.invocation, ['executablePath', 'executableDigest', 'argv', 'cwdPath', 'environment', 'digest'], line, 'invocation'); exact(value.invocation.environment, ['values', 'credentialSlotId', 'endpoint', 'organization', 'project'], line, 'environment');
  const request = value.request; const invocation = value.invocation; const environment = invocation.environment as Record<string, unknown>;
  const bytesBase64 = string(request.bytesBase64, line, 'request.bytesBase64'); const bytes = Buffer.from(bytesBase64, 'base64');
  if (bytes.toString('base64') !== bytesBase64 || bytes.length !== integer(request.byteLength, line, 'request.byteLength', true) || sha(bytes) !== digest(request.digest, line, 'request.digest')) throw new ProposalExecutionError(line, 'request bytes are invalid');
  if (request.channel !== 'stdin' || request.envelope !== 'prompt-injected-reminder/v1') throw new ProposalExecutionError(line, 'request transport is invalid');
  if (!Array.isArray(invocation.argv) || invocation.argv.some((arg) => typeof arg !== 'string' || arg.includes('\0'))) throw new ProposalExecutionError(line, 'invocation.argv must be NUL-free strings');
  for (const [key, item] of Object.entries(environment.values as Record<string, unknown>)) { if (key.includes('\0')) throw new ProposalExecutionError(line, 'environment value key must be NUL-free'); string(item, line, 'environment.values entry'); }
  const p: ProposalExecutionPlan = { schemaVersion: value.schemaVersion, trialId: string(value.trialId, line, 'trialId'), judgmentId: string(value.judgmentId, line, 'judgmentId'), runId: string(value.runId, line, 'runId'), scenarioId: string(value.scenarioId, line, 'scenarioId'), host: value.host as 'claude' | 'codex', policyId: string(value.policyId, line, 'policyId'), condition: value.condition as ProposalCondition, adapter: value.adapter as ProposalExecutionAdapter, adapterVersion: string(value.adapterVersion, line, 'adapterVersion'), requestedModel: string(value.requestedModel, line, 'requestedModel'), scenarioDigest: digest(value.scenarioDigest, line, 'scenarioDigest'), policyDigest: digest(value.policyDigest, line, 'policyDigest'), assignmentDigest: digest(value.assignmentDigest, line, 'assignmentDigest'), request: { bytesBase64, byteLength: bytes.length, digest: request.digest as string, channel: 'stdin', envelope: 'prompt-injected-reminder/v1' }, invocation: { executablePath: string(invocation.executablePath, line, 'invocation.executablePath'), executableDigest: digest(invocation.executableDigest, line, 'invocation.executableDigest'), argv: invocation.argv as string[], cwdPath: string(invocation.cwdPath, line, 'invocation.cwdPath'), environment: { values: environment.values as Record<string, string>, credentialSlotId: string(environment.credentialSlotId, line, 'environment.credentialSlotId'), endpoint: nullableString(environment.endpoint, line, 'environment.endpoint'), organization: nullableString(environment.organization, line, 'environment.organization'), project: nullableString(environment.project, line, 'environment.project') }, digest: digest(invocation.digest, line, 'invocation.digest') }, planDigest: digest(value.planDigest, line, 'planDigest') };
  const values = p.invocation.environment.values as Record<string, string>; const claudeUserEnvironment = p.host === 'claude' && Object.hasOwn(values, 'USER') && Object.hasOwn(values, 'LOGNAME'); const expectedEnvironmentKeys = p.host === 'codex' ? ['CODEX_HOME', 'HOME', 'LANG', 'PATH', 'TMPDIR'] : claudeUserEnvironment ? ['HOME', 'LANG', 'LOGNAME', 'PATH', 'TMPDIR', 'USER'] : ['HOME', 'LANG', 'PATH', 'TMPDIR']; const executable = basename(p.invocation.executablePath).toLowerCase(); const credentialIdentity = p.host === 'codex' ? values.CODEX_HOME! : claudeUserEnvironment ? `${values.HOME!}\0${values.USER!}\0${values.LOGNAME!}` : values.HOME!;
  if ((p.host !== 'codex' && p.host !== 'claude') || (p.condition !== 'control' && p.condition !== 'caveat') || p.adapter !== `${p.host}-cli` || !isAbsolute(p.invocation.executablePath) || !isAbsolute(p.invocation.cwdPath) || !['default'].includes(p.invocation.environment.endpoint ?? '') || p.invocation.environment.organization !== null || p.invocation.environment.project !== null || Object.keys(values).sort().join('\0') !== expectedEnvironmentKeys.join('\0') || !isAbsolute(values.HOME!) || (p.host === 'codex' && !isAbsolute(values.CODEX_HOME!)) || values.TMPDIR !== p.invocation.cwdPath || values.LANG !== 'C.UTF-8' || p.invocation.environment.credentialSlotId !== sha(`${p.host}\0${credentialIdentity}`) || !(executable === p.host || executable === `${p.host}.cmd` || executable === `${p.host}.exe`) || canonicalProposalExecutionJson(p.invocation.argv) !== canonicalProposalExecutionJson(expectedProposalExecutionArgv(p.host, p.requestedModel))) throw new ProposalExecutionError(line, 'plan fields are invalid');
  const invocationData = { executablePath: p.invocation.executablePath, executableDigest: p.invocation.executableDigest, argv: p.invocation.argv, cwdPath: p.invocation.cwdPath, environment: p.invocation.environment };
  if (sha(canonicalProposalExecutionJson(invocationData)) !== p.invocation.digest) throw new ProposalExecutionError(line, 'invocation digest mismatch');
  const { planDigest, ...planData } = p; if (sha(canonicalProposalExecutionJson(planData)) !== planDigest) throw new ProposalExecutionError(line, 'planDigest mismatch'); return p;
}
function rfc3339(value: unknown, line: number, field: string): number { const text = string(value, line, field); const match = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{1,9})?Z$/.exec(text); if (!match) throw new ProposalExecutionError(line, `${field} must be strict RFC3339 UTC`); const time = Date.parse(text); const date = new Date(time); if (!Number.isFinite(time) || date.getUTCFullYear() !== Number(match[1]) || date.getUTCMonth() + 1 !== Number(match[2]) || date.getUTCDate() !== Number(match[3]) || date.getUTCHours() !== Number(match[4]) || date.getUTCMinutes() !== Number(match[5]) || date.getUTCSeconds() !== Number(match[6])) throw new ProposalExecutionError(line, `${field} must be strict RFC3339 UTC`); return time; }
function parseReceipt(value: unknown, line: number): ProposalExecutionReceipt {
  if (!record(value)) throw new ProposalExecutionError(line, 'receipt must be a plain object'); exact(value, ['schemaVersion', 'trialId', 'runId', 'planDigest', 'invocationDigest', 'status', 'startedAt', 'completedAt', 'cliVersion', 'exitCode', 'providerRunId', 'reportedModel', 'modelProvenance', 'requestSubmission', 'submittedRequestDigest', 'submittedByteLength', 'rawStdoutDigest', 'rawStderrDigest', 'outputDigest', 'receiptDigest'], line, 'receipt');
  if (value.schemaVersion !== PROPOSAL_EXECUTION_SCHEMA_VERSION) throw new ProposalExecutionError(line, 'receipt schemaVersion is invalid');
  const status = value.status; if (status !== 'completed' && status !== 'unavailable' && status !== 'protocol_error' && status !== 'tool_attempted' && status !== 'nonzero_exit') throw new ProposalExecutionError(line, 'receipt status is invalid');
  const started = rfc3339(value.startedAt, line, 'startedAt'); if (rfc3339(value.completedAt, line, 'completedAt') < started) throw new ProposalExecutionError(line, 'completedAt precedes startedAt');
  const exitCode = value.exitCode === null ? null : integer(value.exitCode, line, 'exitCode'); const providerRunId = nullableString(value.providerRunId, line, 'providerRunId'); const reportedModel = nullableString(value.reportedModel, line, 'reportedModel'); const modelProvenance = value.modelProvenance; const outputDigest = value.outputDigest === null ? null : digest(value.outputDigest, line, 'outputDigest');
  if (modelProvenance !== 'provider_reported' && modelProvenance !== 'requested_only') throw new ProposalExecutionError(line, 'receipt modelProvenance is invalid');
  const requestSubmission = value.requestSubmission; if (requestSubmission !== 'not_attempted' && requestSubmission !== 'passed_to_spawn_sync' && requestSubmission !== 'indeterminate') throw new ProposalExecutionError(line, 'receipt requestSubmission is invalid'); const submittedRequestDigest = value.submittedRequestDigest === null ? null : digest(value.submittedRequestDigest, line, 'submittedRequestDigest'); const submittedByteLength = value.submittedByteLength === null ? null : integer(value.submittedByteLength, line, 'submittedByteLength', true);
  if ((modelProvenance === 'provider_reported') !== (reportedModel !== null) || (requestSubmission === 'passed_to_spawn_sync') !== (submittedRequestDigest !== null && submittedByteLength !== null) || (status === 'completed' && (exitCode !== 0 || providerRunId === null || outputDigest === null || requestSubmission !== 'passed_to_spawn_sync')) || (status === 'nonzero_exit' && (exitCode === null || exitCode === 0 || outputDigest !== null || requestSubmission !== 'passed_to_spawn_sync')) || (status === 'unavailable' && (exitCode !== null || outputDigest !== null)) || ((status === 'protocol_error' || status === 'tool_attempted') && (exitCode !== 0 || outputDigest !== null || requestSubmission !== 'passed_to_spawn_sync'))) throw new ProposalExecutionError(line, 'receipt status invariant failed');
  const r: ProposalExecutionReceipt = { schemaVersion: value.schemaVersion, trialId: string(value.trialId, line, 'trialId'), runId: string(value.runId, line, 'runId'), planDigest: digest(value.planDigest, line, 'planDigest'), invocationDigest: digest(value.invocationDigest, line, 'invocationDigest'), status, startedAt: value.startedAt as string, completedAt: value.completedAt as string, cliVersion: string(value.cliVersion, line, 'cliVersion'), exitCode, providerRunId, reportedModel, modelProvenance, requestSubmission, submittedRequestDigest, submittedByteLength, rawStdoutDigest: digest(value.rawStdoutDigest, line, 'rawStdoutDigest'), rawStderrDigest: digest(value.rawStderrDigest, line, 'rawStderrDigest'), outputDigest, receiptDigest: digest(value.receiptDigest, line, 'receiptDigest') };
  const { receiptDigest, ...data } = r; if (sha(canonicalProposalExecutionJson(data)) !== receiptDigest) throw new ProposalExecutionError(line, 'receiptDigest mismatch'); return r;
}
function parse<T>(source: string, parser: (value: unknown, line: number) => T, label: string): T[] { const lines = source.split(/\r?\n/); if (lines.at(-1) === '') lines.pop(); if (!lines.length) throw new ProposalExecutionError(null, `${label} artifact has no records`, 0); return lines.map((raw, index) => { if (!raw.trim()) throw new ProposalExecutionError(index + 1, 'empty JSONL record'); try { return parser(JSON.parse(raw), index + 1); } catch (error) { if (error instanceof ProposalExecutionError) throw error; throw new ProposalExecutionError(index + 1, 'malformed JSON'); } }); }
export const parseProposalExecutionPlansJsonl = (source: string) => parse(source, parsePlan, 'plans');
export const parseProposalExecutionReceiptsJsonl = (source: string) => parse(source, parseReceipt, 'receipts');

function protocolLines(source: string): Record<string, unknown>[] {
  const lines = source.split(/\r?\n/); if (lines.at(-1) === '') lines.pop();
  if (!lines.length) throw new Error('empty protocol stream');
  return lines.map((line) => { if (!line.trim()) throw new Error('empty protocol record'); const value: unknown = JSON.parse(line); if (!record(value)) throw new Error('protocol record is not an object'); return value; });
}
function protocolError(modelProvenance: ProposalExecutionModelProvenance = 'requested_only'): ParsedProposalExecutionOutput { return { status: 'protocol_error', providerRunId: null, reportedModel: null, modelProvenance, output: null }; }

/** Parse the public `codex exec --json` JSONL protocol. Codex does not report the effective model in this stream. */
export function parseCodexProposalExecutionJsonl(source: string): ParsedProposalExecutionOutput {
  try {
    const events = protocolLines(source); let providerRunId: string | null = null; let turnStarted = 0; let turnCompleted = 0; let toolAttempted = false; let invalid = false; let output: string | null = null;
    const toolTypes = new Set(['command_execution', 'file_change', 'mcp_tool_call', 'collab_tool_call', 'web_search']); const passiveTypes = new Set(['agent_message', 'reasoning', 'todo_list']);
    events.forEach((event, index) => {
      const type = event.type;
      if (type === 'thread.started') { if (index !== 0 || providerRunId !== null || typeof event.thread_id !== 'string' || event.thread_id.length === 0) invalid = true; else providerRunId = event.thread_id; return; }
      if (providerRunId === null || turnCompleted > 0) { invalid = true; return; }
      if (type === 'turn.started') { turnStarted++; return; }
      if (type === 'turn.completed') { turnCompleted++; return; }
      if (type === 'turn.failed' || type === 'error') { invalid = true; return; }
      if (type !== 'item.started' && type !== 'item.updated' && type !== 'item.completed') { invalid = true; return; }
      if (!record(event.item) || typeof event.item.type !== 'string') { invalid = true; return; }
      const itemType = event.item.type;
      if (toolTypes.has(itemType)) { toolAttempted = true; return; }
      if (itemType === 'error' || !passiveTypes.has(itemType)) { invalid = true; return; }
      if (type === 'item.completed' && itemType === 'agent_message') { if (typeof event.item.text !== 'string' || event.item.text.length === 0) invalid = true; else output = event.item.text; }
    });
    if (toolAttempted) return { status: 'tool_attempted', providerRunId, reportedModel: null, modelProvenance: 'requested_only', output: null };
    if (invalid || providerRunId === null || turnStarted !== 1 || turnCompleted !== 1 || output === null) return protocolError();
    return { status: 'completed', providerRunId, reportedModel: null, modelProvenance: 'requested_only', output };
  } catch { return protocolError(); }
}

/** Parse Claude Code `--output-format stream-json`; provider model evidence comes from the terminal result usage. */
export function parseClaudeProposalExecutionJsonl(source: string, expectedModel: string): ParsedProposalExecutionOutput {
  try {
    const events = protocolLines(source); let providerRunId: string | null = null; let initModel: string | null = null; let terminalResult: unknown = null; let resultSeen = false; let toolAttempted = false; let invalid = false; const assistantModels = new Set<string>();
    events.forEach((event, index) => {
      const type = event.type; const sessionId = event.session_id;
      if (typeof sessionId !== 'string' || sessionId.length === 0 || (providerRunId !== null && providerRunId !== sessionId)) { invalid = true; return; } providerRunId ??= sessionId;
      if (type === 'system' && event.subtype === 'init') { if (index !== 0 || initModel !== null || typeof event.model !== 'string' || event.model.length === 0) invalid = true; else initModel = event.model; return; }
      if (type === 'system' && event.subtype === 'thinking_tokens') { if (initModel === null || resultSeen || typeof event.estimated_tokens !== 'number' || !Number.isSafeInteger(event.estimated_tokens) || event.estimated_tokens < 0 || typeof event.estimated_tokens_delta !== 'number' || !Number.isSafeInteger(event.estimated_tokens_delta) || event.estimated_tokens_delta < 0) invalid = true; return; }
      if (initModel === null || resultSeen) { invalid = true; return; }
      if (type === 'assistant') {
        if (!record(event.message) || typeof event.message.model !== 'string' || !Array.isArray(event.message.content)) { invalid = true; return; }
        assistantModels.add(event.message.model);
        for (const block of event.message.content) { if (!record(block) || typeof block.type !== 'string') invalid = true; else if (block.type === 'tool_use' || block.type === 'server_tool_use') toolAttempted = true; else if (!['text', 'thinking', 'redacted_thinking'].includes(block.type)) invalid = true; }
        return;
      }
      if (type === 'rate_limit_event') { if (!record(event.rate_limit_info)) invalid = true; return; }
      if (type === 'result') { terminalResult = event; resultSeen = true; return; }
      invalid = true;
    });
    if (!record(terminalResult)) return protocolError(); const result = terminalResult;
    if (toolAttempted || (Array.isArray(result.permission_denials) && result.permission_denials.length > 0)) return { status: 'tool_attempted', providerRunId, reportedModel: null, modelProvenance: 'requested_only', output: null };
    if (invalid || providerRunId === null || initModel === null || result.subtype !== 'success' || result.is_error !== false || typeof result.result !== 'string' || result.result.length === 0 || !record(result.modelUsage)) return protocolError();
    const models = Object.keys(result.modelUsage); if (!models.includes(expectedModel) || assistantModels.size !== 1 || !assistantModels.has(expectedModel) || initModel !== expectedModel) return protocolError();
    return { status: 'completed', providerRunId, reportedModel: expectedModel, modelProvenance: 'provider_reported', output: result.result };
  } catch { return protocolError(); }
}
export function buildProposalRequestBytes(scenario: ProposalScenario, condition: ProposalCondition): Buffer { return Buffer.from(condition === 'control' ? scenario.scenario : `${scenario.scenario}\n\n<caveat-reminder>\n${scenario.reminder}\n</caveat-reminder>`, 'utf8'); }

function policyIsCliV1(policy: ProposalPolicy): boolean { return policy.hostAdapter === `${policy.host}-cli/prompt-injected-reminder/v1` && policy.permissionMode === 'read-only-no-tools' && policy.systemInstructions === '' && policy.developerInstructions === '' && record(policy.toolSchema) && Object.keys(policy.toolSchema).length === 0 && Array.isArray(policy.toolAllowlist) && policy.toolAllowlist.length === 0 && record(policy.sampling) && policy.sampling.temperature === null && policy.sampling.topP === null && policy.sampling.seed === null; }
export function validateProposalExecutionPlans(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], plans: ProposalExecutionPlan[]): void {
  scenarios = scenarios.map((item) => parseProposalScenariosJsonl(JSON.stringify(item))[0]!); policies = policies.map((item) => parseProposalPoliciesJsonl(JSON.stringify(item))[0]!); assignments = assignments.map((item) => parseProposalAssignmentsJsonl(JSON.stringify(item))[0]!);
  if (!scenarios.length || !policies.length || !assignments.length || !plans.length) throw new ProposalExecutionError(null, 'all plan artifacts require at least one record', 0);
  const scenarioById = new Map<string, ProposalScenario>(); for (const scenario of scenarios) { if (scenarioById.has(scenario.scenarioId)) throw new ProposalExecutionError(null, 'duplicate scenarioId'); scenarioById.set(scenario.scenarioId, scenario); }
  const policyById = new Map<string, ProposalPolicy>(); for (const policy of policies) { if (policyById.has(policy.policyId)) throw new ProposalExecutionError(null, 'duplicate policyId'); if (!policyIsCliV1(policy)) throw new ProposalExecutionError(null, 'CLI v1 policy is not fixed'); policyById.set(policy.policyId, policy); }
  const expected = new Map<string, { assignment: ProposalAssignment; run: ProposalAssignment['runs'][number]; condition: ProposalCondition }>(); const blocks = new Set<string>(); const identifiers = new Set<string>();
  for (const assignment of assignments) { const block = [assignment.scenarioId, assignment.host, assignment.model, assignment.policyDigest].join('\0'); if (blocks.has(block)) throw new ProposalExecutionError(null, 'duplicate assignment block'); blocks.add(block); const policy = policyById.get(assignment.policyId); if (!scenarioById.has(assignment.scenarioId) || !policy || policy.host !== assignment.host || policy.model !== assignment.model || policy.policyDigest !== assignment.policyDigest) throw new ProposalExecutionError(null, 'assignment has no matching scenario or policy'); const conditions = assignedConditions(assignment); for (const run of assignment.runs) { for (const id of [run.trialId, run.judgmentId, run.runId]) { if (identifiers.has(id)) throw new ProposalExecutionError(null, 'assignment run identifiers are globally duplicated'); identifiers.add(id); } expected.set(run.trialId, { assignment, run, condition: conditions.get(run.runId)! }); } }
  const seen = new Set<string>(); const runtimeByBlock = new Map<string, string>(); for (const raw of plans) { const plan = parsePlan(raw, 1); const expectedRun = expected.get(plan.trialId); const scenario = scenarioById.get(plan.scenarioId); const policy = policyById.get(plan.policyId); if (!expectedRun || !scenario || !policy || seen.has(plan.trialId) || expectedRun.run.runId !== plan.runId || expectedRun.run.judgmentId !== plan.judgmentId || expectedRun.assignment.scenarioId !== plan.scenarioId || expectedRun.assignment.host !== plan.host || expectedRun.assignment.model !== plan.requestedModel || expectedRun.assignment.policyId !== plan.policyId || expectedRun.assignment.policyDigest !== plan.policyDigest || expectedRun.condition !== plan.condition || plan.scenarioDigest !== scenario.scenarioDigest || plan.assignmentDigest !== proposalAssignmentDigest(expectedRun.assignment) || !buildProposalRequestBytes(scenario, plan.condition).equals(Buffer.from(plan.request.bytesBase64, 'base64'))) throw new ProposalExecutionError(null, 'plan provenance mismatch'); const block = [plan.scenarioId, plan.host, plan.requestedModel, plan.policyDigest].join('\0'); const runtime = proposalExecutionRuntimeDigest(plan); if (runtimeByBlock.has(block) && runtimeByBlock.get(block) !== runtime) throw new ProposalExecutionError(null, 'runtime differs within comparison block'); runtimeByBlock.set(block, runtime); seen.add(plan.trialId); }
  if (seen.size !== expected.size) throw new ProposalExecutionError(null, 'every assignment run requires exactly one plan', expected.size - seen.size);
}
export function prepareProposalExecutionPlans(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], runtimes: ProposalExecutionRuntime[]): ProposalExecutionPlan[] {
  const scenarioById = new Map(scenarios.map((item) => [item.scenarioId, item])); const policyById = new Map(policies.map((item) => [item.policyId, item])); const runtimeByTrial = new Map<string, ProposalExecutionRuntime>(); for (const runtime of runtimes) { if (runtimeByTrial.has(runtime.trialId)) throw new ProposalExecutionError(null, 'runtime trialId is duplicated'); runtimeByTrial.set(runtime.trialId, runtime); }
  const plans: ProposalExecutionPlan[] = []; for (const assignment of assignments) { const scenario = scenarioById.get(assignment.scenarioId); const policy = policyById.get(assignment.policyId); if (!scenario || !policy) throw new ProposalExecutionError(null, 'runtime has no matching scenario or policy'); for (const run of assignment.runs) { const runtime = runtimeByTrial.get(run.trialId); if (!runtime) throw new ProposalExecutionError(null, 'every assignment run requires one runtime'); const condition = assignedConditions(assignment).get(run.runId)!; const requestBytes = buildProposalRequestBytes(scenario, condition); const invocationData = { executablePath: runtime.executablePath, executableDigest: runtime.executableDigest, argv: expectedProposalExecutionArgv(assignment.host, assignment.model), cwdPath: runtime.cwdPath, environment: runtime.environment }; const invocation = { ...invocationData, digest: sha(canonicalProposalExecutionJson(invocationData)) }; const data = { schemaVersion: PROPOSAL_EXECUTION_SCHEMA_VERSION as typeof PROPOSAL_EXECUTION_SCHEMA_VERSION, trialId: run.trialId, judgmentId: run.judgmentId, runId: run.runId, scenarioId: scenario.scenarioId, host: assignment.host, policyId: policy.policyId, condition, adapter: `${assignment.host}-cli` as ProposalExecutionAdapter, adapterVersion: runtime.adapterVersion, requestedModel: assignment.model, scenarioDigest: scenario.scenarioDigest, policyDigest: policy.policyDigest, assignmentDigest: proposalAssignmentDigest(assignment), request: { bytesBase64: requestBytes.toString('base64'), byteLength: requestBytes.length, digest: sha(requestBytes), channel: 'stdin' as const, envelope: 'prompt-injected-reminder/v1' as const }, invocation }; plans.push({ ...data, planDigest: sha(canonicalProposalExecutionJson(data)) }); } }
  if (runtimeByTrial.size !== plans.length) throw new ProposalExecutionError(null, 'runtime has extra trial'); validateProposalExecutionPlans(scenarios, policies, assignments, plans); return plans;
}
export function validateProposalExecutionProvenance(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], plans: ProposalExecutionPlan[], receipts: ProposalExecutionReceipt[]): void {
  validateProposalExecutionPlans(scenarios, policies, assignments, plans);
  scenarios = scenarios.map((item) => parseProposalScenariosJsonl(JSON.stringify(item))[0]!); policies = policies.map((item) => parseProposalPoliciesJsonl(JSON.stringify(item))[0]!); assignments = assignments.map((item) => parseProposalAssignmentsJsonl(JSON.stringify(item))[0]!);
  if (!scenarios.length || !policies.length || !assignments.length || !plans.length || !receipts.length) throw new ProposalExecutionError(null, 'all artifacts require at least one record', 0);
  const scenarioById = new Map<string, ProposalScenario>(); for (const scenario of scenarios) { if (scenarioById.has(scenario.scenarioId)) throw new ProposalExecutionError(null, 'duplicate scenarioId'); scenarioById.set(scenario.scenarioId, scenario); }
  const policyById = new Map<string, ProposalPolicy>(); for (const policy of policies) { if (policyById.has(policy.policyId)) throw new ProposalExecutionError(null, 'duplicate policyId'); if (!policyIsCliV1(policy)) throw new ProposalExecutionError(null, 'CLI v1 policy is not fixed'); policyById.set(policy.policyId, policy); }
  const expected = new Map<string, { assignment: ProposalAssignment; run: ProposalAssignment['runs'][number]; condition: ProposalCondition }>(); const blocks = new Set<string>(); const identifiers = new Set<string>();
  for (const assignment of assignments) { const block = [assignment.scenarioId, assignment.host, assignment.model, assignment.policyDigest].join('\0'); if (blocks.has(block)) throw new ProposalExecutionError(null, 'duplicate assignment block'); blocks.add(block); const policy = policyById.get(assignment.policyId); if (!scenarioById.has(assignment.scenarioId) || !policy || policy.host !== assignment.host || policy.model !== assignment.model || policy.policyDigest !== assignment.policyDigest) throw new ProposalExecutionError(null, 'assignment has no matching scenario or policy'); const conditions = assignedConditions(assignment); for (const run of assignment.runs) { for (const id of [run.trialId, run.judgmentId, run.runId]) { if (identifiers.has(id)) throw new ProposalExecutionError(null, 'assignment run identifiers are globally duplicated'); identifiers.add(id); } if (expected.has(run.trialId)) throw new ProposalExecutionError(null, 'assignment trialId is globally duplicated'); expected.set(run.trialId, { assignment, run, condition: conditions.get(run.runId)! }); } }
  const planByTrial = new Map<string, ProposalExecutionPlan>(); const runtimeByBlock = new Map<string, string>(); for (const raw of plans) { const plan = parsePlan(raw, 1); const expectedRun = expected.get(plan.trialId); const scenario = scenarioById.get(plan.scenarioId); const policy = policyById.get(plan.policyId); if (!expectedRun || !scenario || !policy || planByTrial.has(plan.trialId) || expectedRun.run.runId !== plan.runId || expectedRun.run.judgmentId !== plan.judgmentId || expectedRun.assignment.scenarioId !== plan.scenarioId || expectedRun.assignment.host !== plan.host || expectedRun.assignment.model !== plan.requestedModel || expectedRun.assignment.policyId !== plan.policyId || expectedRun.assignment.policyDigest !== plan.policyDigest || expectedRun.condition !== plan.condition || plan.scenarioDigest !== scenario.scenarioDigest || plan.assignmentDigest !== proposalAssignmentDigest(expectedRun.assignment) || plan.adapter !== (plan.host === 'codex' ? 'codex-cli' : 'claude-cli') || !buildProposalRequestBytes(scenario, plan.condition).equals(Buffer.from(plan.request.bytesBase64, 'base64'))) throw new ProposalExecutionError(null, 'plan provenance mismatch'); const block = [plan.scenarioId, plan.host, plan.requestedModel, plan.policyDigest].join('\0'); const runtime = proposalExecutionRuntimeDigest(plan); if (runtimeByBlock.has(block) && runtimeByBlock.get(block) !== runtime) throw new ProposalExecutionError(null, 'runtime differs within comparison block'); runtimeByBlock.set(block, runtime); planByTrial.set(plan.trialId, plan); }
  if (planByTrial.size !== expected.size) throw new ProposalExecutionError(null, 'every assignment run requires exactly one plan', expected.size - planByTrial.size);
  const receiptByTrial = new Map<string, ProposalExecutionReceipt>(); const reportedByBlock = new Map<string, string>(); for (const raw of receipts) { const receipt = parseReceipt(raw, 1); const plan = planByTrial.get(receipt.trialId); if (!plan || receiptByTrial.has(receipt.trialId) || receipt.runId !== plan.runId || receipt.planDigest !== plan.planDigest || receipt.invocationDigest !== plan.invocation.digest || receipt.cliVersion !== plan.adapterVersion || (receipt.requestSubmission === 'passed_to_spawn_sync' && (receipt.submittedRequestDigest !== plan.request.digest || receipt.submittedByteLength !== plan.request.byteLength)) || (receipt.requestSubmission !== 'passed_to_spawn_sync' && (receipt.submittedRequestDigest !== null || receipt.submittedByteLength !== null)) || (receipt.status === 'completed' && plan.host === 'claude' && (receipt.modelProvenance !== 'provider_reported' || receipt.reportedModel !== plan.requestedModel)) || (receipt.status === 'completed' && plan.host === 'codex' && (receipt.modelProvenance !== 'requested_only' || receipt.reportedModel !== null))) throw new ProposalExecutionError(null, 'receipt provenance mismatch'); if (receipt.status === 'completed' && receipt.reportedModel !== null) { const block = [plan.scenarioId, plan.host, plan.policyDigest].join('\0'); const previous = reportedByBlock.get(block); if (previous !== undefined && previous !== receipt.reportedModel) throw new ProposalExecutionError(null, 'reported model differs within comparison block'); reportedByBlock.set(block, receipt.reportedModel); } receiptByTrial.set(receipt.trialId, receipt); }
  if (receiptByTrial.size !== expected.size) throw new ProposalExecutionError(null, 'every assignment run requires exactly one receipt', expected.size - receiptByTrial.size);
}
export function summarizeProposalExecutionStatuses(plans: ProposalExecutionPlan[], receipts: ProposalExecutionReceipt[]) { const blank = () => ({ denominator: 0, unclearCount: 0, statuses: { completed: 0, unavailable: 0, protocol_error: 0, tool_attempted: 0, nonzero_exit: 0 } }); const result: Record<ProposalCondition, ReturnType<typeof blank>> = { control: blank(), caveat: blank() }; const receiptByTrial = new Map(receipts.map((receipt) => [receipt.trialId, receipt])); for (const plan of plans) { const bucket = result[plan.condition]; const receipt = receiptByTrial.get(plan.trialId); bucket.denominator++; if (!receipt || receipt.status !== 'completed') bucket.unclearCount++; if (receipt) bucket.statuses[receipt.status]++; } return result; }
