import { createHash } from 'node:crypto';
import { isAbsolute, relative, resolve, sep } from 'node:path';

export const PROPOSAL_EVAL_SCHEMA_VERSION = 'proposal-eval/v1';
export const PROPOSAL_EVAL_RUNNER_VERSION = 'proposal-eval-runner/v1';
export type ProposalCondition = 'control' | 'caveat';
export type ProposalJudgmentValue = 'yes' | 'no' | 'unclear';
type Host = 'claude' | 'codex';

export interface ProposalScenario { scenarioId: string; scenario: string; evidence: Array<{ reference: string; content: string; digest: string }>; knownBadClaims: string[]; validSolutionRubric: string[]; reminder: string; scenarioDigest: string; reminderDigest: string; }
export interface ProposalPolicy { policyId: string; host: Host; model: string; hostAdapter: string; systemInstructions: string; developerInstructions: string; toolSchema: unknown; toolAllowlist: string[]; permissionMode: string; sampling: { temperature: number | null; topP: number | null; seed: number | null }; policyDigest: string; }
export interface ProposalAssignment { scenarioId: string; host: Host; model: string; policyId: string; policyDigest: string; seed: string; algorithm: 'sha256-sort-halves/v1'; runs: Array<{ trialId: string; judgmentId: string; runId: string }>; }
export interface ProposalTrial { trialId: string; scenarioId: string; host: Host; model: string; policyId: string; policyDigest: string; runId: string; condition: ProposalCondition; assignment: 'randomized'; scenarioDigest: string; reminderDigest: string | null; output: string; }
export interface ProposalReviewPacket { judgmentId: string; scenario: string; evidence: Array<{ reference: string; content: string; digest: string }>; knownBadClaims: string[]; validSolutionRubric: string[]; output: string; packetDigest: string; }
export interface ProposalJudgment { judgmentId: string; packetDigest: string; knownBadClaimEmitted: ProposalJudgmentValue; validSolutionSupplied: ProposalJudgmentValue; judge: string; judgePrompt: string; judgePromptDigest: string; maskedReviewAttested: true; }

export interface ProposalBound { numerator: number; denominator: number; value: number; }
export interface ProposalRateBounds { lower: ProposalBound; upper: ProposalBound; unclearCount: number; }
export interface ProposalConditionMetrics { trialCount: number; knownBadClaimRate: ProposalRateBounds; validSolutionRate: ProposalRateBounds; safeAndUsefulRate: ProposalRateBounds; }
export interface ProposalDifferenceInterval { lower: number; upper: number; }
export interface ProposalScenarioMetrics { scenarioId: string; conditions: Record<ProposalCondition, ProposalConditionMetrics>; rateDifference: Record<'knownBadClaimRate' | 'validSolutionRate' | 'safeAndUsefulRate', ProposalDifferenceInterval>; }
export interface ProposalStratumMetrics { host: Host; model: string; policyDigest: string; scenarioCount: number; scenarios: ProposalScenarioMetrics[]; macroRateDifference: Record<'knownBadClaimRate' | 'validSolutionRate' | 'safeAndUsefulRate', ProposalDifferenceInterval>; }
export interface ProposalEvalMetrics { schemaVersion: typeof PROPOSAL_EVAL_SCHEMA_VERSION; runnerVersion: typeof PROPOSAL_EVAL_RUNNER_VERSION; strata: ProposalStratumMetrics[]; }

export class ProposalEvalArtifactError extends Error {
  constructor(line: number | null, reason: string, count = 1) { super(`proposal evaluation artifact mismatch: ${line === null ? 'aggregate' : `line ${line}`}; count ${count}; ${reason}`); this.name = 'ProposalEvalArtifactError'; }
}

const DIGEST = /^[0-9a-f]{64}$/;
const JUDGMENT_ID = /^[0-9a-f]{32}$/;
function sha256(value: string): string { return createHash('sha256').update(Buffer.from(value, 'utf8')).digest('hex'); }
function stableJson(value: unknown, seen = new Set<object>()): string { if (value === null || typeof value === 'string' || typeof value === 'boolean') return JSON.stringify(value); if (typeof value === 'number') { if (!Number.isFinite(value)) throw new ProposalEvalArtifactError(null, 'canonical JSON requires finite numbers'); return JSON.stringify(value); } if (Array.isArray(value)) { if (seen.has(value)) throw new ProposalEvalArtifactError(null, 'canonical JSON rejects cycles'); seen.add(value); const result = `[${value.map((item) => stableJson(item, seen)).join(',')}]`; seen.delete(value); return result; } if (!record(value) || Object.getPrototypeOf(value) !== Object.prototype) throw new ProposalEvalArtifactError(null, 'canonical JSON requires plain JSON values'); if (seen.has(value)) throw new ProposalEvalArtifactError(null, 'canonical JSON rejects cycles'); seen.add(value); const result = `{${Object.keys(value).sort().map((key) => `${JSON.stringify(key)}:${stableJson(value[key], seen)}`).join(',')}}`; seen.delete(value); return result; }
function record(value: unknown): value is Record<string, unknown> { return typeof value === 'object' && value !== null && !Array.isArray(value); }
function keys(value: Record<string, unknown>, expected: string[], line: number, label: string): void {
  const actual = Object.keys(value);
  if (actual.length !== expected.length || actual.some((key) => !expected.includes(key))) throw new ProposalEvalArtifactError(line, `${label} has unknown or missing keys`);
}
function text(value: unknown, line: number, field: string): string { if (typeof value !== 'string' || value.trim().length === 0) throw new ProposalEvalArtifactError(line, `${field} must be a nonempty string`); return value; }
function identifier(value: unknown, line: number, field: string): string { const result = text(value, line, field); if (result.includes('\0')) throw new ProposalEvalArtifactError(line, `${field} must not contain NUL`); return result; }
function digest(value: unknown, line: number, field: string): string { const result = text(value, line, field); if (!DIGEST.test(result)) throw new ProposalEvalArtifactError(line, `${field} must be a lowercase SHA-256 digest`); return result; }
function stringArray(value: unknown, line: number, field: string): string[] { if (!Array.isArray(value)) throw new ProposalEvalArtifactError(line, `${field} must be an array`); return value.map((item, index) => text(item, line, `${field}[${index}]`)); }
function host(value: unknown, line: number): Host { if (value !== 'claude' && value !== 'codex') throw new ProposalEvalArtifactError(line, 'host is invalid'); return value; }

function parseScenario(value: unknown, line: number): ProposalScenario {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'scenario must be an object');
  keys(value, ['scenarioId', 'scenario', 'evidence', 'knownBadClaims', 'validSolutionRubric', 'reminder', 'scenarioDigest', 'reminderDigest'], line, 'scenario');
  if (!Array.isArray(value.evidence)) throw new ProposalEvalArtifactError(line, 'evidence must be an array');
  const evidence = value.evidence.map((item, index) => {
    if (!record(item)) throw new ProposalEvalArtifactError(line, `evidence[${index}] must be an object`);
    keys(item, ['reference', 'content', 'digest'], line, `evidence[${index}]`);
    const result = { reference: text(item.reference, line, `evidence[${index}].reference`), content: text(item.content, line, `evidence[${index}].content`), digest: digest(item.digest, line, `evidence[${index}].digest`) };
    if (sha256(result.content) !== result.digest) throw new ProposalEvalArtifactError(line, 'evidence digest does not match content');
    return result;
  });
  if (evidence.length === 0) throw new ProposalEvalArtifactError(line, 'evidence must have at least one item');
  const knownBadClaims = stringArray(value.knownBadClaims, line, 'knownBadClaims');
  const validSolutionRubric = stringArray(value.validSolutionRubric, line, 'validSolutionRubric');
  if (knownBadClaims.length === 0 || validSolutionRubric.length === 0) throw new ProposalEvalArtifactError(line, 'scenario criteria arrays must have at least one item');
  const result = { scenarioId: identifier(value.scenarioId, line, 'scenarioId'), scenario: text(value.scenario, line, 'scenario'), evidence, knownBadClaims, validSolutionRubric, reminder: text(value.reminder, line, 'reminder'), scenarioDigest: digest(value.scenarioDigest, line, 'scenarioDigest'), reminderDigest: digest(value.reminderDigest, line, 'reminderDigest') };
  const canonical = JSON.stringify({ scenario: result.scenario, evidence: result.evidence.map(({ reference, digest: itemDigest }) => ({ reference, digest: itemDigest })), knownBadClaims: result.knownBadClaims, validSolutionRubric: result.validSolutionRubric });
  if (sha256(canonical) !== result.scenarioDigest) throw new ProposalEvalArtifactError(line, 'scenarioDigest does not match canonical scenario');
  if (sha256(result.reminder) !== result.reminderDigest) throw new ProposalEvalArtifactError(line, 'reminderDigest does not match reminder');
  return result;
}
function parseAssignment(value: unknown, line: number): ProposalAssignment {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'assignment must be an object');
  keys(value, ['scenarioId', 'host', 'model', 'policyId', 'policyDigest', 'seed', 'algorithm', 'runs'], line, 'assignment');
  if (value.algorithm !== 'sha256-sort-halves/v1') throw new ProposalEvalArtifactError(line, 'assignment algorithm is invalid');
  if (!Array.isArray(value.runs)) throw new ProposalEvalArtifactError(line, 'assignment runs must be an array');
  const runs = value.runs.map((item, index) => { if (!record(item)) throw new ProposalEvalArtifactError(line, `runs[${index}] must be an object`); keys(item, ['trialId', 'judgmentId', 'runId'], line, `runs[${index}]`); const judgmentId = text(item.judgmentId, line, `runs[${index}].judgmentId`); if (!JUDGMENT_ID.test(judgmentId)) throw new ProposalEvalArtifactError(line, 'judgmentId must be opaque lowercase 32hex'); return { trialId: identifier(item.trialId, line, `runs[${index}].trialId`), judgmentId, runId: identifier(item.runId, line, `runs[${index}].runId`) }; });
  return { scenarioId: identifier(value.scenarioId, line, 'scenarioId'), host: host(value.host, line), model: identifier(value.model, line, 'model'), policyId: identifier(value.policyId, line, 'policyId'), policyDigest: digest(value.policyDigest, line, 'policyDigest'), seed: digest(value.seed, line, 'seed'), algorithm: 'sha256-sort-halves/v1', runs };
}
function parseTrial(value: unknown, line: number): ProposalTrial {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'trial must be an object');
  keys(value, ['trialId', 'scenarioId', 'host', 'model', 'policyId', 'policyDigest', 'runId', 'condition', 'assignment', 'scenarioDigest', 'reminderDigest', 'output'], line, 'trial');
  if (value.condition !== 'control' && value.condition !== 'caveat') throw new ProposalEvalArtifactError(line, 'condition is invalid');
  if (value.assignment !== 'randomized') throw new ProposalEvalArtifactError(line, 'assignment must be randomized');
  const condition = value.condition;
  if (condition === 'control' && value.reminderDigest !== null) throw new ProposalEvalArtifactError(line, 'control reminderDigest must be null');
  return { trialId: identifier(value.trialId, line, 'trialId'), scenarioId: identifier(value.scenarioId, line, 'scenarioId'), host: host(value.host, line), model: identifier(value.model, line, 'model'), policyId: identifier(value.policyId, line, 'policyId'), policyDigest: digest(value.policyDigest, line, 'policyDigest'), runId: identifier(value.runId, line, 'runId'), condition, assignment: 'randomized', scenarioDigest: digest(value.scenarioDigest, line, 'scenarioDigest'), reminderDigest: condition === 'control' ? null : digest(value.reminderDigest, line, 'reminderDigest'), output: text(value.output, line, 'output') };
}
function parseJudgment(value: unknown, line: number): ProposalJudgment {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'judgment must be an object');
  keys(value, ['judgmentId', 'packetDigest', 'knownBadClaimEmitted', 'validSolutionSupplied', 'judge', 'judgePrompt', 'judgePromptDigest', 'maskedReviewAttested'], line, 'judgment');
  const judgmentId = text(value.judgmentId, line, 'judgmentId'); if (!JUDGMENT_ID.test(judgmentId)) throw new ProposalEvalArtifactError(line, 'judgmentId must be opaque lowercase 32hex');
  if (!['yes', 'no', 'unclear'].includes(value.knownBadClaimEmitted as string) || !['yes', 'no', 'unclear'].includes(value.validSolutionSupplied as string)) throw new ProposalEvalArtifactError(line, 'judgment value is invalid');
  const judgePrompt = text(value.judgePrompt, line, 'judgePrompt'); const judgePromptDigest = digest(value.judgePromptDigest, line, 'judgePromptDigest');
  if (sha256(judgePrompt) !== judgePromptDigest) throw new ProposalEvalArtifactError(line, 'judgePromptDigest does not match judgePrompt');
  if (value.maskedReviewAttested !== true) throw new ProposalEvalArtifactError(line, 'maskedReviewAttested must be true');
  return { judgmentId, packetDigest: digest(value.packetDigest, line, 'packetDigest'), knownBadClaimEmitted: value.knownBadClaimEmitted as ProposalJudgmentValue, validSolutionSupplied: value.validSolutionSupplied as ProposalJudgmentValue, judge: identifier(value.judge, line, 'judge'), judgePrompt, judgePromptDigest, maskedReviewAttested: true };
}
function parsePolicy(value: unknown, line: number): ProposalPolicy {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'policy must be an object');
  keys(value, ['policyId', 'host', 'model', 'hostAdapter', 'systemInstructions', 'developerInstructions', 'toolSchema', 'toolAllowlist', 'permissionMode', 'sampling', 'policyDigest'], line, 'policy');
  if (!record(value.sampling)) throw new ProposalEvalArtifactError(line, 'sampling must be an object'); const sampling = value.sampling as Record<string, unknown>; keys(sampling, ['temperature', 'topP', 'seed'], line, 'sampling');
  const sample = (name: 'temperature' | 'topP' | 'seed') => { const item = sampling[name]; if (item !== null && (typeof item !== 'number' || !Number.isFinite(item))) throw new ProposalEvalArtifactError(line, `sampling.${name} must be finite number or null`); if (name === 'seed' && item !== null && !Number.isInteger(item)) throw new ProposalEvalArtifactError(line, 'sampling.seed must be integer or null'); return item as number | null; };
  const policy = { policyId: identifier(value.policyId, line, 'policyId'), host: host(value.host, line), model: identifier(value.model, line, 'model'), hostAdapter: identifier(value.hostAdapter, line, 'hostAdapter'), systemInstructions: typeof value.systemInstructions === 'string' ? value.systemInstructions : (() => { throw new ProposalEvalArtifactError(line, 'systemInstructions must be a string'); })(), developerInstructions: typeof value.developerInstructions === 'string' ? value.developerInstructions : (() => { throw new ProposalEvalArtifactError(line, 'developerInstructions must be a string'); })(), toolSchema: value.toolSchema, toolAllowlist: stringArray(value.toolAllowlist, line, 'toolAllowlist').map((item) => identifier(item, line, 'toolAllowlist item')), permissionMode: identifier(value.permissionMode, line, 'permissionMode'), sampling: { temperature: sample('temperature'), topP: sample('topP'), seed: sample('seed') }, policyDigest: digest(value.policyDigest, line, 'policyDigest') };
  const canonical = stableJson({ host: policy.host, model: policy.model, hostAdapter: policy.hostAdapter, systemInstructions: policy.systemInstructions, developerInstructions: policy.developerInstructions, toolSchema: policy.toolSchema, toolAllowlist: policy.toolAllowlist, permissionMode: policy.permissionMode, sampling: policy.sampling });
  if (sha256(canonical) !== policy.policyDigest) throw new ProposalEvalArtifactError(line, 'policyDigest does not match canonical policy'); return policy;
}
function parseReviewPacket(value: unknown, line: number): ProposalReviewPacket {
  if (!record(value)) throw new ProposalEvalArtifactError(line, 'review packet must be an object'); keys(value, ['judgmentId', 'scenario', 'evidence', 'knownBadClaims', 'validSolutionRubric', 'output', 'packetDigest'], line, 'review packet');
  if (!Array.isArray(value.evidence)) throw new ProposalEvalArtifactError(line, 'packet evidence must be an array'); const evidence = value.evidence.map((item, index) => { if (!record(item)) throw new ProposalEvalArtifactError(line, 'packet evidence must be an object'); keys(item, ['reference', 'content', 'digest'], line, 'packet evidence'); const result = { reference: text(item.reference, line, 'evidence.reference'), content: text(item.content, line, 'evidence.content'), digest: digest(item.digest, line, 'evidence.digest') }; if (sha256(result.content) !== result.digest) throw new ProposalEvalArtifactError(line, 'evidence digest does not match content'); return result; });
  const judgmentId = text(value.judgmentId, line, 'judgmentId'); if (!JUDGMENT_ID.test(judgmentId)) throw new ProposalEvalArtifactError(line, 'judgmentId must be opaque lowercase 32hex'); const packet = { judgmentId, scenario: text(value.scenario, line, 'scenario'), evidence, knownBadClaims: stringArray(value.knownBadClaims, line, 'knownBadClaims'), validSolutionRubric: stringArray(value.validSolutionRubric, line, 'validSolutionRubric'), output: text(value.output, line, 'output'), packetDigest: digest(value.packetDigest, line, 'packetDigest') }; const canonical = JSON.stringify({ judgmentId: packet.judgmentId, scenario: packet.scenario, evidence: packet.evidence, knownBadClaims: packet.knownBadClaims, validSolutionRubric: packet.validSolutionRubric, output: packet.output }); if (sha256(canonical) !== packet.packetDigest) throw new ProposalEvalArtifactError(line, 'packetDigest does not match packet'); return packet;
}
function parseJsonl<T>(source: string, parser: (value: unknown, line: number) => T, label: string): T[] { const lines = source.split(/\r?\n/); if (lines.at(-1) === '') lines.pop(); if (lines.length === 0) throw new ProposalEvalArtifactError(null, `${label} artifact has no records`, 0); return lines.map((raw, index) => { const line = index + 1; if (raw.trim().length === 0) throw new ProposalEvalArtifactError(line, 'empty JSONL record'); try { return parser(JSON.parse(raw), line); } catch (error) { if (error instanceof ProposalEvalArtifactError) throw error; throw new ProposalEvalArtifactError(line, 'malformed JSON'); } }); }
export const parseProposalScenariosJsonl = (source: string) => parseJsonl(source, parseScenario, 'scenarios');
export const parseProposalPoliciesJsonl = (source: string) => parseJsonl(source, parsePolicy, 'policies');
export const parseProposalAssignmentsJsonl = (source: string) => parseJsonl(source, parseAssignment, 'assignments');
export const parseProposalTrialsJsonl = (source: string) => parseJsonl(source, parseTrial, 'trials');
export const parseProposalReviewPacketsJsonl = (source: string) => parseJsonl(source, parseReviewPacket, 'review packets');
export const parseProposalJudgmentsJsonl = (source: string) => parseJsonl(source, parseJudgment, 'judgments');

function blockKey(item: { scenarioId: string; host: Host; model: string; policyDigest: string }): string { return [item.scenarioId, item.host, item.model, item.policyDigest].join('\0'); }
export function assignedConditions(assignment: ProposalAssignment): Map<string, ProposalCondition> {
  if (assignment.runs.length < 4 || assignment.runs.length % 2 !== 0) throw new ProposalEvalArtifactError(null, 'assignment runs must be an even count of at least 4', assignment.runs.length);
  const seen = new Set<string>();
  for (const run of assignment.runs) for (const id of [run.trialId, run.judgmentId, run.runId]) { if (seen.has(id)) throw new ProposalEvalArtifactError(null, 'assignment run identifiers must be unique'); seen.add(id); }
  return new Map([...assignment.runs].sort((a, b) => { const left = `${sha256(`${assignment.seed}\0${a.runId}`)}\0${a.runId}`; const right = `${sha256(`${assignment.seed}\0${b.runId}`)}\0${b.runId}`; return left < right ? -1 : left > right ? 1 : 0; }).map((run, index) => [run.runId, index < assignment.runs.length / 2 ? 'control' : 'caveat']));
}
export function validateProposalArtifacts(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], trials: ProposalTrial[], packets: ProposalReviewPacket[], judgments: ProposalJudgment[]): void {
  ({ scenarios, policies, assignments, trials, packets, judgments } = normalizeProposalArtifacts(scenarios, policies, assignments, trials, packets, judgments));
  const policyById = new Map<string, ProposalPolicy>(); policies.forEach((policy, index) => { if (policyById.has(policy.policyId)) throw new ProposalEvalArtifactError(index + 1, 'duplicate policyId'); policyById.set(policy.policyId, policy); });
  const scenarioById = new Map<string, ProposalScenario>();
  scenarios.forEach((scenario, index) => { if (scenarioById.has(scenario.scenarioId)) throw new ProposalEvalArtifactError(index + 1, 'duplicate scenarioId'); scenarioById.set(scenario.scenarioId, scenario); });
  const assignmentsByBlock = new Map<string, ProposalAssignment>(); const mappedTrials = new Map<string, { assignment: ProposalAssignment; judgmentId: string; condition: ProposalCondition }>(); const mappedJudgments = new Map<string, string>();
  assignments.forEach((assignment, index) => { const key = blockKey(assignment); const policy = policyById.get(assignment.policyId); if (!scenarioById.has(assignment.scenarioId) || !policy || policy.host !== assignment.host || policy.model !== assignment.model || policy.policyDigest !== assignment.policyDigest) throw new ProposalEvalArtifactError(index + 1, 'assignment has no matching scenario or policy'); if (assignmentsByBlock.has(key)) throw new ProposalEvalArtifactError(index + 1, 'duplicate assignment block'); assignmentsByBlock.set(key, assignment); const conditions = assignedConditions(assignment); for (const run of assignment.runs) { if (mappedTrials.has(run.trialId) || mappedJudgments.has(run.judgmentId)) throw new ProposalEvalArtifactError(index + 1, 'assignment identifiers are globally duplicated'); mappedTrials.set(run.trialId, { assignment, judgmentId: run.judgmentId, condition: conditions.get(run.runId)! }); mappedJudgments.set(run.judgmentId, run.trialId); } });
  if (assignments.length === 0 || trials.length === 0 || packets.length === 0 || judgments.length === 0 || scenarios.length === 0 || policies.length === 0) throw new ProposalEvalArtifactError(null, 'all artifacts require at least one record', 0);
  const trialsById = new Map<string, ProposalTrial>();
  trials.forEach((trial, index) => { const line = index + 1; if (trialsById.has(trial.trialId)) throw new ProposalEvalArtifactError(line, 'duplicate trialId'); const mapped = mappedTrials.get(trial.trialId); const policy = policyById.get(trial.policyId); if (!mapped) throw new ProposalEvalArtifactError(line, 'trial has no assignment mapping'); const scenario = scenarioById.get(trial.scenarioId); if (!scenario || !policy || mapped.assignment.scenarioId !== trial.scenarioId || mapped.assignment.host !== trial.host || mapped.assignment.model !== trial.model || mapped.assignment.policyId !== trial.policyId || mapped.assignment.policyDigest !== trial.policyDigest || policy.host !== trial.host || policy.model !== trial.model || policy.policyDigest !== trial.policyDigest || !mapped.assignment.runs.some((run) => run.trialId === trial.trialId && run.runId === trial.runId)) throw new ProposalEvalArtifactError(line, 'trial does not match assignment mapping'); if (trial.condition !== mapped.condition || trial.scenarioDigest !== scenario.scenarioDigest || (trial.condition === 'control' ? trial.reminderDigest !== null : trial.reminderDigest !== scenario.reminderDigest)) throw new ProposalEvalArtifactError(line, 'trial manifest fields do not match assignment or scenario'); trialsById.set(trial.trialId, trial); });
  if (trialsById.size !== mappedTrials.size) throw new ProposalEvalArtifactError(null, 'every assignment run requires exactly one trial', mappedTrials.size - trialsById.size);
  const packetById = new Map<string, ProposalReviewPacket>(); packets.forEach((packet, index) => { if (packetById.has(packet.judgmentId)) throw new ProposalEvalArtifactError(index + 1, 'duplicate review packet judgmentId'); const trialId = mappedJudgments.get(packet.judgmentId); const trial = trialId ? trialsById.get(trialId) : undefined; const scenario = trial ? scenarioById.get(trial.scenarioId) : undefined; if (!trial || !scenario) throw new ProposalEvalArtifactError(index + 1, 'review packet has no assignment mapping'); const expected = reviewPacket(packet.judgmentId, scenario, trial); if (JSON.stringify(packet) !== JSON.stringify(expected)) throw new ProposalEvalArtifactError(index + 1, 'review packet does not match manifest'); packetById.set(packet.judgmentId, packet); }); if (packetById.size !== mappedTrials.size) throw new ProposalEvalArtifactError(null, 'every assignment run requires exactly one review packet', mappedTrials.size - packetById.size);
  const judgmentsById = new Map<string, ProposalJudgment>(); const judgeByBlock = new Map<string, { judge: string; prompt: string }>();
  judgments.forEach((judgment, index) => { const line = index + 1; if (judgmentsById.has(judgment.judgmentId)) throw new ProposalEvalArtifactError(line, 'duplicate judgmentId'); const trialId = mappedJudgments.get(judgment.judgmentId); if (!trialId || !packetById.has(judgment.judgmentId)) throw new ProposalEvalArtifactError(line, 'judgment has no packet mapping'); const trial = trialsById.get(trialId); if (!trial || judgment.packetDigest !== packetById.get(judgment.judgmentId)!.packetDigest) throw new ProposalEvalArtifactError(line, 'judgment packetDigest does not match review packet'); const key = blockKey(trial); const judge = judgeByBlock.get(key); if (judge !== undefined && (judge.judge !== judgment.judge || judge.prompt !== judgment.judgePromptDigest)) throw new ProposalEvalArtifactError(line, 'judge differs within scenario/host/model/policy block'); judgeByBlock.set(key, { judge: judgment.judge, prompt: judgment.judgePromptDigest }); judgmentsById.set(judgment.judgmentId, judgment); });
  if (judgmentsById.size !== mappedTrials.size) throw new ProposalEvalArtifactError(null, 'every assignment run requires exactly one judgment', mappedTrials.size - judgmentsById.size);
}

function normalizeProposalArtifacts(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], trials: ProposalTrial[], packets: ProposalReviewPacket[], judgments: ProposalJudgment[]): { scenarios: ProposalScenario[]; policies: ProposalPolicy[]; assignments: ProposalAssignment[]; trials: ProposalTrial[]; packets: ProposalReviewPacket[]; judgments: ProposalJudgment[] } {
  return { scenarios: scenarios.map((item, index) => parseScenario(item, index + 1)), policies: policies.map((item, index) => parsePolicy(item, index + 1)), assignments: assignments.map((item, index) => parseAssignment(item, index + 1)), trials: trials.map((item, index) => parseTrial(item, index + 1)), packets: packets.map((item, index) => parseReviewPacket(item, index + 1)), judgments: judgments.map((item, index) => parseJudgment(item, index + 1)) };
}

function bounds(items: Array<{ judgment: ProposalJudgment }>, metric: 'known' | 'valid' | 'safe'): ProposalRateBounds { const denominator = items.length; const lower = items.filter(({ judgment }) => metric === 'known' ? judgment.knownBadClaimEmitted === 'yes' : metric === 'valid' ? judgment.validSolutionSupplied === 'yes' : judgment.knownBadClaimEmitted === 'no' && judgment.validSolutionSupplied === 'yes').length; const upper = items.filter(({ judgment }) => metric === 'known' ? judgment.knownBadClaimEmitted !== 'no' : metric === 'valid' ? judgment.validSolutionSupplied !== 'no' : judgment.knownBadClaimEmitted !== 'yes' && judgment.validSolutionSupplied !== 'no').length; const unclearCount = items.filter(({ judgment }) => metric === 'known' ? judgment.knownBadClaimEmitted === 'unclear' : metric === 'valid' ? judgment.validSolutionSupplied === 'unclear' : judgment.knownBadClaimEmitted === 'unclear' || judgment.validSolutionSupplied === 'unclear').length; return { lower: { numerator: lower, denominator, value: lower / denominator }, upper: { numerator: upper, denominator, value: upper / denominator }, unclearCount }; }
function metricsFor(items: Array<{ judgment: ProposalJudgment }>): ProposalConditionMetrics { return { trialCount: items.length, knownBadClaimRate: bounds(items, 'known'), validSolutionRate: bounds(items, 'valid'), safeAndUsefulRate: bounds(items, 'safe') }; }
function difference(treatment: ProposalRateBounds, control: ProposalRateBounds): ProposalDifferenceInterval { return { lower: treatment.lower.value - control.upper.value, upper: treatment.upper.value - control.lower.value }; }
function reviewPacket(judgmentId: string, scenario: ProposalScenario, trial: ProposalTrial): ProposalReviewPacket { const data = { judgmentId, scenario: scenario.scenario, evidence: scenario.evidence, knownBadClaims: scenario.knownBadClaims, validSolutionRubric: scenario.validSolutionRubric, output: trial.output }; return { ...data, packetDigest: sha256(JSON.stringify(data)) }; }
export function prepareProposalReviewPackets(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], trials: ProposalTrial[]): ProposalReviewPacket[] {
  const normalized = normalizeProposalArtifacts(scenarios, policies, assignments, trials, [], []); const scenarioById = new Map<string, ProposalScenario>(); const policyById = new Map<string, ProposalPolicy>(); const trialById = new Map<string, ProposalTrial>(); const blocks = new Set<string>(); const runTrialIds = new Set<string>(); const judgmentIds = new Set<string>(); const packets: ProposalReviewPacket[] = [];
  for (const scenario of normalized.scenarios) { if (scenarioById.has(scenario.scenarioId)) throw new ProposalEvalArtifactError(null, 'duplicate scenarioId'); scenarioById.set(scenario.scenarioId, scenario); }
  for (const policy of normalized.policies) { if (policyById.has(policy.policyId)) throw new ProposalEvalArtifactError(null, 'duplicate policyId'); policyById.set(policy.policyId, policy); }
  for (const assignment of normalized.assignments) { const key = blockKey(assignment); if (blocks.has(key)) throw new ProposalEvalArtifactError(null, 'duplicate assignment block'); blocks.add(key); assignedConditions(assignment); for (const run of assignment.runs) { if (runTrialIds.has(run.trialId) || judgmentIds.has(run.judgmentId)) throw new ProposalEvalArtifactError(null, 'assignment identifiers are globally duplicated'); runTrialIds.add(run.trialId); judgmentIds.add(run.judgmentId); } }
  for (const trial of normalized.trials) { if (trialById.has(trial.trialId)) throw new ProposalEvalArtifactError(null, 'duplicate trialId'); trialById.set(trial.trialId, trial); }
  for (const assignment of normalized.assignments) { const policy = policyById.get(assignment.policyId); if (!scenarioById.has(assignment.scenarioId) || !policy || policy.host !== assignment.host || policy.model !== assignment.model || policy.policyDigest !== assignment.policyDigest) throw new ProposalEvalArtifactError(null, 'assignment has no matching scenario or policy'); const conditions = assignedConditions(assignment); for (const run of assignment.runs) { const trial = trialById.get(run.trialId); const scenario = scenarioById.get(assignment.scenarioId)!; if (!trial || trial.scenarioId !== assignment.scenarioId || trial.host !== assignment.host || trial.model !== assignment.model || trial.policyId !== assignment.policyId || trial.policyDigest !== assignment.policyDigest || trial.runId !== run.runId || trial.condition !== conditions.get(run.runId) || trial.scenarioDigest !== scenario.scenarioDigest || (trial.condition === 'control' ? trial.reminderDigest !== null : trial.reminderDigest !== scenario.reminderDigest)) throw new ProposalEvalArtifactError(null, 'trial does not match assignment mapping'); packets.push(reviewPacket(run.judgmentId, scenario, trial)); } }
  if (trialById.size !== packets.length) throw new ProposalEvalArtifactError(null, 'every assignment run requires exactly one trial', packets.length - trialById.size); return packets;
}
export function evaluateProposalArtifacts(scenarios: ProposalScenario[], policies: ProposalPolicy[], assignments: ProposalAssignment[], trials: ProposalTrial[], packets: ProposalReviewPacket[], judgments: ProposalJudgment[]): ProposalEvalMetrics {
  ({ scenarios, policies, assignments, trials, packets, judgments } = normalizeProposalArtifacts(scenarios, policies, assignments, trials, packets, judgments));
  validateProposalArtifacts(scenarios, policies, assignments, trials, packets, judgments);
  const byJudgment = new Map(judgments.map((item) => [item.judgmentId, item])); const assignmentRuns = new Map(assignments.flatMap((assignment) => assignment.runs.map((run) => [run.trialId, run.judgmentId]))); const joined = trials.map((trial) => ({ trial, judgment: byJudgment.get(assignmentRuns.get(trial.trialId)!)! }));
  const byScenarioBlock = new Map<string, typeof joined>();
  for (const item of joined) { const key = blockKey(item.trial); const group = byScenarioBlock.get(key) ?? []; group.push(item); byScenarioBlock.set(key, group); }
  const scenarioMetrics = new Map<string, ProposalScenarioMetrics>();
  for (const [key, items] of byScenarioBlock) { const conditions = Object.fromEntries((['control', 'caveat'] as const).map((condition) => [condition, metricsFor(items.filter(({ trial }) => trial.condition === condition))])) as Record<ProposalCondition, ProposalConditionMetrics>; scenarioMetrics.set(key, { scenarioId: items[0]!.trial.scenarioId, conditions, rateDifference: { knownBadClaimRate: difference(conditions.caveat.knownBadClaimRate, conditions.control.knownBadClaimRate), validSolutionRate: difference(conditions.caveat.validSolutionRate, conditions.control.validSolutionRate), safeAndUsefulRate: difference(conditions.caveat.safeAndUsefulRate, conditions.control.safeAndUsefulRate) } }); }
  const byStratum = new Map<string, Array<[string, ProposalScenarioMetrics]>>();
  for (const entry of scenarioMetrics) { const key = entry[0].split('\0').slice(1).join('\0'); const group = byStratum.get(key) ?? []; group.push(entry); byStratum.set(key, group); }
  const strata = [...byStratum.values()].map((entries) => { const [hostValue, model, policyDigest] = entries[0]![0].split('\0').slice(1) as [Host, string, string]; const macro = (metric: keyof ProposalScenarioMetrics['rateDifference']) => ({ lower: entries.reduce((sum, [, value]) => sum + value.rateDifference[metric].lower, 0) / entries.length, upper: entries.reduce((sum, [, value]) => sum + value.rateDifference[metric].upper, 0) / entries.length }); return { host: hostValue, model, policyDigest, scenarioCount: entries.length, scenarios: entries.map(([, value]) => value), macroRateDifference: { knownBadClaimRate: macro('knownBadClaimRate'), validSolutionRate: macro('validSolutionRate'), safeAndUsefulRate: macro('safeAndUsefulRate') } }; });
  return { schemaVersion: PROPOSAL_EVAL_SCHEMA_VERSION, runnerVersion: PROPOSAL_EVAL_RUNNER_VERSION, strata };
}
export function isPathInside(base: string, candidate: string): boolean {
  const rel = relative(resolve(base), resolve(candidate));
  return rel === '' || (rel !== '..' && !rel.startsWith(`..${sep}`) && !isAbsolute(rel));
}
