import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { simpleGit, type SimpleGit } from 'simple-git';
import { parseMarkdown } from './frontmatter.js';
import { walkMarkdown } from './indexer.js';
import type { Logger } from './db.js';
import type { CaveatConfig } from './config.js';
import type { ResolvedPaths } from './paths.js';
import { classifyVisibility } from './visibility.js';

export interface PublishFile { relPath: string; content: Buffer; }
export interface PublishInvalid { relPath: string; reason: string; }
export interface PublishSet { files: PublishFile[]; invalid: PublishInvalid[]; }

export function collectPublishSet(entriesDir: string): PublishSet {
  const files: PublishFile[] = [];
  const invalid: PublishInvalid[] = [];
  if (!existsSync(entriesDir)) return { files, invalid };
  for (const path of walkMarkdown(entriesDir)) {
    const relPath = relative(entriesDir, path).replace(/\\/g, '/');
    const content = readFileSync(path);
    try {
      const visibility = classifyVisibility(parseMarkdown(content.toString('utf-8')).frontmatter.visibility);
      if (visibility === 'public') files.push({ relPath, content });
      else if (visibility === 'invalid') invalid.push({ relPath, reason: 'visibility must be exactly public or private' });
    } catch (err) {
      invalid.push({ relPath, reason: err instanceof Error ? err.message : String(err) });
    }
  }
  return { files, invalid };
}

export async function preparePublishMirror(opts: { mirrorDir: string; target: string; git?: SimpleGit }): Promise<void> {
  const git = opts.git ?? simpleGit();
  if (!existsSync(opts.mirrorDir)) {
    mkdirSync(dirname(opts.mirrorDir), { recursive: true });
    await git.clone(opts.target, opts.mirrorDir);
  } else {
    const mirrorGit = simpleGit(opts.mirrorDir);
    const old = (await mirrorGit.raw(['remote', 'get-url', 'origin'])).trim();
    if (old !== opts.target) {
      throw new Error(`publish mirror points at ${old} but publishTarget is ${opts.target} — remove ${opts.mirrorDir} and re-run`);
    }
  }
  const mirrorGit = simpleGit(opts.mirrorDir);
  await mirrorGit.fetch('origin');
  const head = (await mirrorGit.raw(['symbolic-ref', '--quiet', 'refs/remotes/origin/HEAD']).catch(() => '')).trim();
  if (head) await mirrorGit.reset(['--hard', head]);
  // git clean -ffdx: remove any untracked debris (incl. ignored) a crashed
  // prior run may have left, so it cannot be re-committed and leaked (C4).
  await mirrorGit.raw(['clean', '-ffdx']);
}

export function publishReadme(fileCount: number, files: PublishFile[]): string {
  const categories = [...new Set(files.map((f) => f.relPath.split('/')[0]).filter(Boolean))].sort();
  return [
    '# Caveat-Public',
    '',
    'This repository is generated by `caveat publish`. Do not edit it by hand.',
    '',
    'Subscribe with `caveat community add <https URL or username>`.',
    '',
    `Public entries: ${fileCount}`,
    `Categories: ${categories.length ? categories.join(', ') : '(none)'}`,
    '',
    'Caveat: https://github.com/kitepon-rgb/Caveat',
    '',
  ].join('\n');
}

// The mirror is a pure generated artifact: every path except .git is replaced
// on each publish. Deleting only entries/ would let a tracked file elsewhere
// in the remote's history survive reset+clean and ride along in our commits.
export function writeMirror(opts: { mirrorDir: string; files: PublishFile[]; readme: string }): void {
  for (const item of readdirSync(opts.mirrorDir, { withFileTypes: true })) {
    if (item.name === '.git') continue;
    rmSync(join(opts.mirrorDir, item.name), { recursive: true, force: true });
  }
  const entries = join(opts.mirrorDir, 'entries');
  for (const file of opts.files) {
    const target = join(entries, file.relPath);
    mkdirSync(dirname(target), { recursive: true });
    writeFileSync(target, file.content);
  }
  writeFileSync(join(opts.mirrorDir, 'README.md'), opts.readme, 'utf-8');
}

function* walkAllFiles(root: string): Generator<string> {
  for (const item of readdirSync(root, { withFileTypes: true })) {
    if (item.name === '.git') continue;
    const full = join(root, item.name);
    if (item.isDirectory()) yield* walkAllFiles(full);
    else yield full;
  }
}

// Sole pass/fail criterion for the mirror (docs/06 C7): the WHOLE tree except
// .git must consist of the generated README plus entries/**/*.md that each
// parse and classify as exactly public. Any unexpected path fails.
export function verifyMirror(mirrorDir: string): { fileCount: number } {
  const entriesRoot = join(mirrorDir, 'entries');
  const bad: string[] = [];
  let fileCount = 0;
  for (const path of walkAllFiles(mirrorDir)) {
    const relToMirror = relative(mirrorDir, path).replace(/\\/g, '/');
    if (relToMirror === 'README.md') continue;
    if (!relToMirror.startsWith('entries/')) {
      bad.push(`${relToMirror}: unexpected file outside entries/`);
      continue;
    }
    if (!relToMirror.endsWith('.md')) {
      bad.push(`${relToMirror}: unexpected non-markdown file`);
      continue;
    }
    fileCount++;
    const relPath = relative(entriesRoot, path).replace(/\\/g, '/');
    try {
      const visibility = classifyVisibility(parseMarkdown(readFileSync(path, 'utf-8')).frontmatter.visibility);
      if (visibility !== 'public') bad.push(`${relPath}: visibility is ${visibility}`);
    } catch (err) { bad.push(`${relPath}: ${err instanceof Error ? err.message : String(err)}`); }
  }
  if (bad.length) throw new Error(`publish mirror verification failed:\n${bad.join('\n')}`);
  return { fileCount };
}

export interface PublishOwnOptions {
  paths: Pick<ResolvedPaths, 'entriesDir' | 'publishMirrorDir'>;
  config: CaveatConfig;
  logger: Logger;
  confirmImpl: (question: string) => boolean;
  isTty?: () => boolean;
  dryRun?: boolean;
  yes?: boolean;
}
export interface PublishResult { fileCount: number; changed: boolean; dryRun: boolean; }

function stagedChanges(raw: string): { lines: string[]; added: number; modified: number; deleted: number } {
  const lines = raw.trim() ? raw.trim().split(/\r?\n/) : [];
  let added = 0; let modified = 0; let deleted = 0;
  for (const line of lines) { if (line.startsWith('A')) added++; else if (line.startsWith('D')) deleted++; else modified++; }
  return { lines, added, modified, deleted };
}

export async function publishOwn(opts: PublishOwnOptions): Promise<PublishResult> {
  if (!opts.config.publishTarget) throw new Error('publishTarget is not configured');
  const collected = collectPublishSet(opts.paths.entriesDir);
  if (collected.invalid.length) throw new Error(`cannot publish invalid entries:\n${collected.invalid.map((x) => `${x.relPath}: ${x.reason}`).join('\n')}`);
  await preparePublishMirror({ mirrorDir: opts.paths.publishMirrorDir, target: opts.config.publishTarget });
  writeMirror({ mirrorDir: opts.paths.publishMirrorDir, files: collected.files, readme: publishReadme(collected.files.length, collected.files) });
  const verified = verifyMirror(opts.paths.publishMirrorDir);
  if (verified.fileCount !== collected.files.length) throw new Error(`publish mirror file count mismatch: expected ${collected.files.length}, got ${verified.fileCount}`);
  const git = simpleGit(opts.paths.publishMirrorDir);
  await git.add('-A');
  const changes = stagedChanges(await git.raw(['diff', '--cached', '--name-status']));
  if (!changes.lines.length) { opts.logger.info('no changes to publish'); return { fileCount: verified.fileCount, changed: false, dryRun: Boolean(opts.dryRun) }; }
  for (const line of changes.lines) opts.logger.info(line);
  if (opts.dryRun) return { fileCount: verified.fileCount, changed: true, dryRun: true };
  const question = `publish ${changes.lines.length} file change(s)? [y/N]`;
  if (!opts.yes) {
    if (!(opts.isTty ?? (() => Boolean(process.stdin.isTTY)))()) throw new Error(`${question}; rerun with --yes to approve non-interactively`);
    if (!opts.confirmImpl(question)) throw new Error('publish cancelled');
  }
  await git.commit(`caveat publish: ${verified.fileCount} public entries (+${changes.added} ~${changes.modified} -${changes.deleted})`);
  const branch = (await git.raw(['symbolic-ref', '--short', 'HEAD'])).trim();
  await git.push('origin', branch, ['-u']);
  return { fileCount: verified.fileCount, changed: true, dryRun: false };
}
